### ISSUE TITLE
Sound not working on Arch Linux

### ISSUE THREAD

**Issue by HUg0005** [smcameron/space-nerds-in-space#101]
Hi,
I have two ArchLinux machines, laptop and a desktop. On the desktop snis works flawlessly. On the laptop snis works but the sound (like changing between menus, firing the laser, etc) don't work but the text to speech works, probably as text to speech is handled differently to normal sounds. I am guessing it is a dependency problem but I cannot work out what package it is.
Thanks
EDIT: the laptop install is booted from a USB stick. I am trying to create a ArchLinux based live usb for      launching snis

**Comment by smcameron** [comment]
Probably something to do with portaudio-1.9...  it's getting quite old now and I'm not sure how well maintained it is.  I may need to consider moving to something else.

If you want a much smaller test program that exercises the portaudio code path in a very similar way as space nerds in space, you could try out this thing: 

http://github.com/smcameron/subharmonic-traumaphone

**Comment by HUg0005** [comment]
Ok I have tested your subharmonic-traumaphone (Thats a cool program) on both arch machines. The desktop worked flawlessly but the laptop was silent. So as you expected it is a problem with portaudio. I'll check the packages that are being installed on when the iso is being built.

**Comment by smcameron** [comment]
Have you tried booting your desktop from your USB stick and seeing if that works?   If not, then problem is probably something about the software on the USB (I think this is most likely the case), but if it does work on the desktop, maybe it's some hardware difference.  These days though, basic audio hardware is pretty standardized, so I would not expect any issues.

**Comment by smcameron** [comment]
Also, what version of portaudio is installed?  (Needs to 1.9)

**Comment by HUg0005** [comment]
I have tested the USB live version on the desktop and as we thought, no difference. Portaudio is version 1.9 from the ArchLinux community repo ([LINK](https://www.archlinux.org/packages/community/x86_64/portaudio/)) on both computers. The only difference between the computers is that the desktop has pulseaudio but that shouldn't make a difference.

**Comment by smcameron** [comment]
Ok, I have just added a little program, snis_test_audio.  On my system, I see this:

```
$ make snis_test_audio
$ ./snis_test_audio
Space Nerds In Space audio test program.
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
Portaudio reports 21 sound devices.
Portaudio says the default device is: 20
wwviaudio_initialize_portaudio returned 0
Portaudio reports 21 devices
0: HDA Intel PCH: ALC887-VD Analog (hw:0,0)
1: HDA Intel PCH: ALC887-VD Digital (hw:0,1)
2: HDA Intel PCH: ALC887-VD Alt Analog (hw:0,2)
3: HDA Intel PCH: HDMI 0 (hw:0,3)
4: HDA Intel PCH: HDMI 1 (hw:0,7)
5: HDA Intel PCH: HDMI 2 (hw:0,8)
6: Scarlett 2i2 USB: Audio (hw:1,0)
7: sysdefault
8: front
9: surround21
10: surround40
11: surround41
12: surround50
13: surround51
14: surround71
15: iec958
16: spdif
17: hdmi
18: pulse
19: dmix
20: default
Attempting to play sound... ...finished attempting to play sound
```

You can try alternate devices, for example, I can make it play through my Scarlett 2i2 USB sound device by:

```
 $ ./snis_test_audio 6
Space Nerds In Space audio test program.
Manually setting sound device to 6
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
Portaudio reports 21 sound devices.
Portaudio says the default device is: 20
Using sound device 6
wwviaudio_initialize_portaudio returned 0
Portaudio reports 21 devices
0: HDA Intel PCH: ALC887-VD Analog (hw:0,0)
1: HDA Intel PCH: ALC887-VD Digital (hw:0,1)
2: HDA Intel PCH: ALC887-VD Alt Analog (hw:0,2)
3: HDA Intel PCH: HDMI 0 (hw:0,3)
4: HDA Intel PCH: HDMI 1 (hw:0,7)
5: HDA Intel PCH: HDMI 2 (hw:0,8)
6: Scarlett 2i2 USB: Audio (hw:1,0)
7: sysdefault
8: front
9: surround21
10: surround40
11: surround41
12: surround50
13: surround51
14: surround71
15: iec958
16: spdif
17: hdmi
18: pulse
19: dmix
20: default
Attempting to play sound... ...finished attempting to play sound
```

So, you can see what devices it thinks you have, and try them out.

I also made it so snis_client can use alternate sound devices, e.g.

```
export SNIS_AUDIO_DEVICE=6
```

then launch the game and it will play sounds through my Scarlett 2i2 USB device instead of the default device.

Another thing worth trying.  On my system...

```
$ grep VERSION /etc/*-release
/etc/os-release:VERSION="18.1 (Serena)"
/etc/os-release:VERSION_ID="18.1"
/etc/os-release:VERSION_CODENAME=serena
```

as I was saying, on my system, there is a "Sound Settings..." thing that I can play with.  When the game is running, it shows "ALSA plug-in [snis_client]: ALSA Playback on", and from this GUI Sound Setting thing, I can dynamically switch it to play on either "Built-in Audio Analog Stereo" (which I think is probably what portaudio calls "0: HDA Intel PCH: ALC887-VD Analog (hw:0,0)", and the Scarlett 2i2.  But I think that is via pulse, so if snis_test_audio shows "pulse" as a device it knows, then you should probably do: export SNIS_AUDIO_DEVICE={whatever number portaudio thinks pulse is according to snis_test_audio output}

Hope that helps...

**Comment by HUg0005** [comment]
Alright (sorry It has taken so long), I have done some testing with your snis_test_audio program and found that alsa was defaulting to the hdmi audio output instead of the speakers and alsamixer wasn't changing the device for some strange reason. I installed pulseaudio and pavucontrol and everything works. Thanks for your help.

**Comment by smcameron** [comment]
Thanks.  I added a section to the main web page about troubleshooting audio problems based on this bug report:

http://smcameron.github.io/space-nerds-in-space/#audioproblems

**Comment by HUg0005** [comment]
FYI: I have uploaded the source code for the usb's custom ISO on github. https://github.com/HUg0005/snis-live

**Comment by smcameron** [comment]
Cool.

-- steve
