### ISSUE TITLE
Screenshot alignment issue in mesh_viewer when generating PNGs with Alpha (Fix available)

### ISSUE THREAD

**Issue by cainhopwood** [smcameron/space-nerds-in-space#102]
This is probably not particularly serious. But when I added an alpha channel to the screenshot code (so I could use the screenshots in a blender project), I encountered an off by one error in the following code:

File: graph_dev_opengl.c
```
void graph_dev_grab_framebuffer(unsigned char **buffer, int *width, int *height)
{
	*buffer = malloc(3 * sgc.screen_x * sgc.screen_y);
	*width = sgc.screen_x;
	*height = sgc.screen_y;
	glReadPixels(0, 0, sgc.screen_x - 1, sgc.screen_y - 1,
			GL_RGB, GL_UNSIGNED_BYTE, *buffer);
}
```

The "sgc.screen_x - 1" caused skewed output. Once I removed the -1 the code worked fine as the width of the openGL buffer and the PNG structures were aligned. What is curious is why the error only manifested when RGBA output was requested.

The Fixed code (also adjusted to return alpha) is below. This worked fine.

```
void graph_dev_grab_framebuffer(unsigned char **buffer, int *width, int *height)
{
	*buffer = malloc(4 * sgc.screen_x * sgc.screen_y);
	*width = sgc.screen_x;
	*height = sgc.screen_y;
	glReadPixels(0, 0, sgc.screen_x, sgc.screen_y,
			GL_RGBA, GL_UNSIGNED_BYTE, *buffer);
}

```

BTW, @smcameron Thanks for this I was able to make some nice gas giants to use in a project with your code.

Regards, Cain Hopwood

**Comment by smcameron** [comment]
Thanks.  Pretty sure you also need to set the has_alpha parameter of png_utils_write_png_image().

Committed as 3b0b2d9b215c9b208a19f2b21a7781c28b0bba02

**Comment by cainhopwood** [comment]
Yep, I'd already done that. I was getting nice alpha blended output. It was just increasingly off by one on each  row of pixels.
