### ISSUE TITLE
Game server nickname

### ISSUE THREAD

**Issue by HUg0005** [smcameron/space-nerds-in-space#103]
This is more of a qaustion than an issue, but what is the game server nickname input box and the start game server button ment to do? When I type in a game server nickname and click the start game server button nothing happens; only this output in the terminal:
`snis_server: usage:
snis_server -l lobbyhost -L location [ -m multiverse-location ] [ -n serverick ]
For example: snis_server -l lobbyserver -g 'steves game' -n zuul -L Houston`
which means that its running the snis_server command incorrectly.
Its not much of a problem as I use the snis_launcher but I though I might mention it.

**Comment by smcameron** [comment]
Yeah it's a bug... I always use either quickstart or snis_launcher too.

**Comment by HUg0005** [comment]
What file would contain the code? (I might be able to do something about it)

**Comment by smcameron** [comment]
Yes, that's it. 13913 is where the command is built.

**Comment by smcameron** [comment]
Or 13917.  This code looks obviously wrong.

**Comment by smcameron** [comment]
Looks like commit 4aa186b1 broke it.

**Comment by HUg0005** [comment]
Yea... Im no C programmer

**Comment by smcameron** [comment]
No worries.  I'll take a stab at it probably this weekend.

**Comment by smcameron** [comment]
Alright, the game server nickname thing should be fixed now.  I got rid of the game server nickname (wasn't really used for anything anyway) and replaced it with a solarsystem name input box.  Ideally, that should be a selection from a menu, but at least you can put it in now.  That has to be one of the solarsystems in share/snis/solarsystems.

**Comment by HUg0005** [comment]
Cool. Thanks again.
