### ISSUE TITLE
Standard environment variables for makefile

### ISSUE THREAD

**Issue by the-maldridge** [smcameron/space-nerds-in-space#112]
I noticed that the makefile does not support the standard LDFLAGS and CFLAGS variables for user supplied compilation changes.  Additionally gcc is hard-coded which makes it very difficult to cross compile.

Is this the sort of thing that patches would be accepted for?

**Comment by smcameron** [comment]
Sure. Try to resist the temptation to rewrite the whole makefile though.

**Comment by smcameron** [comment]
Committed as patches, feel free to close this unless there's more remaining to be done.
