### ISSUE TITLE
multiple 'undefined reference to' errors

### ISSUE THREAD

**Issue by tuxutku** [smcameron/space-nerds-in-space#122]
here is my terminal log:
[terminal_log.txt](https://github.com/smcameron/space-nerds-in-space/files/1492271/terminal_log.txt)

**Comment by lisacvuk** [comment]
Seems to me like you haven't installed all the dependencies.  
Try [this.](https://smcameron.github.io/space-nerds-in-space/#buildinstructions)

**Comment by smcameron** [comment]
He's on clearlinux, which is an RPM based distro, so those "apt-get install ..." commands aren't going to work.

Here is a list of the clearlinux RPMs, compared to list for unstable debian sid:
https://distrowatch.com/dwres.php?resource=compare-packages&firstlist=clear&secondlist=debian&firstversions=0&secondversions=0&showall=yes#allpackages

Compare that list of RPMs with this list:

apt-get install build-essential
apt-get install portaudio19-dev
apt-get install libvorbis-dev
apt-get install libgtk2.0-dev
apt-get install git
apt-get install stgit
apt-get install openscad # or get it from http://www.openscad.org/downloads.html
apt-get install libgtkglext1-dev
apt-get install liblua5.2-dev
apt-get install libglew1.5-dev
apt-get install libssl-dev
apt-get install libttspico-utils # for text to speech
apt-get install sox # for "play" command, used by text to speech
apt-get install espeak # optional alternative to libttspico-utils
apt-get install alsa-utils # optional alternative to sox, for "aplay" command
apt-get-install libsdl1.2-dev # optional, only needed for mesh_viewer

and try to find the RPM that corresponds more or less to the debian package, and install those RPMs.

However, right away, I notice that portaudio is not in the list of RPMs for clearlinux.  This is not super surprising, as clearlinux is a distro made for cloud-based containers, and what the hell does a cloud server need audio libraries for?  i.e. clearlinux is a really odd choice of distro for anyone for the purpose of running video games.

**Comment by smcameron** [comment]
Hmm, I noticed this: https://distrowatch.com/table.php?distribution=clear

"Clear Linux is a minimal distribution primarily designed with performance and cloud use-cases in mind. _The operating system upgrades as a whole rather than using individual packages_. Extra software can be added to the system (along with associated dependencies) using pre-compiled bundles which can be accessed through the distribution's swupd software manager." (Emphasis mine).

Yep, clearlinux is a super odd duck.

**Comment by tuxutku** [comment]
yes clearlinux is not rpm based distro, i only using this distro for gaming and rendering becouse of it's performance.
is it there any pre-compiled 64bit version? becouse all depencies are installed by bundles without development header files and i don't know where to get them
many games were working like xonotic, oolite, warsow, spring-lobby etc... and all flatpak applications

**Comment by smcameron** [comment]
No, no precompiled version.

**Comment by tuxutku** [comment]
This is not a issue
by the way i successfully installed the game, it was pretty hard to download and install all the dependencies but it worth it, thanks for such a great game.
