### ISSUE TITLE
3rd person not working

### ISSUE THREAD

**Issue by HUg0005** [smcameron/space-nerds-in-space#124]
When I press 1 on the main menu screen it does not change the view from first to 3rd person.

**Comment by HUg0005** [comment]
That helps a lot. Have to check out snis-keymap.txt. Should probably update the in game help screen as it still says 1.

**Comment by smcameron** [comment]
Updated in game help in commit 0f26e8f875ee44aa6e7c350b1e5eadebe5b4628e
