### ISSUE TITLE
Think about how clients should behave when disconnected

### ISSUE THREAD

**Issue by smcameron** [smcameron/space-nerds-in-space#144]
User suggested that clients should auto-reconnect when disconnected.

I could see that potentially turning into an unintentional DOS attack though, so it would need some kind of safety brakes. It is not a good idea to retry if the retry is just going to fail again.

**Comment by Tapmemer** [comment]
rate limited reconnecting?

**Comment by smcameron** [comment]
The following commits help:

* f8a0150548bf0b0a0a0dfd4d37acefeb36c15edf  Add console mode to demon screen 
* d8929cb74c42b902cf972a282cd9fdade8bc4711  Allow listing clients from demon console
* f6e40001b297a86617136cee54193e1cc468aded  Allow demon console to disconnect clients 
* a68861749d9278b4035e2d5b1be386cd43c7c8c6  Improve client behavior on disconnect 
* 213414e9e925bf342bf2a6e55d22fcbc19cc3c58  Fix deadlock in show_lobbyscreen
* a69318b5a820038570e3a5d8b7e6b75146da97f2 Use stop_gameserver_writer_thread() instead of setting writer_thread_should_die inline

Now on disconnect, clients drop back to the network setup screen, and players can reconnect.  That there's a manual step involved imposes some basic rate limiting (one can only comprehend the screen and click the mouse so fast.)
