### ISSUE TITLE
$PREFIX is not correctly used for scripts

### ISSUE THREAD

**Issue by MCMic** [smcameron/space-nerds-in-space#177]
When building using $PREFIX for instance for the AUR package: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=snis-git

Launching scripts from the demon screen does not work.

It seems the problem is here: https://github.com/smcameron/space-nerds-in-space/blob/master/snis_server.c#L16453
LUASCRIPTDIR is hardcoded instead of being defined by make, or built from PREFIX as is done for assets:
`static char *default_asset_dir = STRPREFIX(PREFIX) "/share/snis";
`

**Comment by MCMic** [comment]
Yes, that fixes it!
I can now start lua scripts fine.

**Comment by smcameron** [comment]
Committed: c762ff0a7433a1e5b3413dc3f9ec8f430e9697bc
