### ISSUE TITLE
Not all luascripts get installed

### ISSUE THREAD

**Issue by MCMic** [smcameron/space-nerds-in-space#178]
When using make install, only 7 luascripts are installed: https://github.com/smcameron/space-nerds-in-space/blob/master/Makefile#L240
But there are a lot more in the repository: https://github.com/smcameron/space-nerds-in-space/tree/master/share/snis/luascripts

I also think it would be better if misson scripts were easy to differentiate from other scripts.
I see two solutions for this:

1. Move missons scripts to a subfolder like luascripts/missions
2. Rename missions scripts to have a common prefix, like MISSION-<name>.lua (and training ones may keep TRAINING- to show they are not real scenarios)

This would help new players like me to know how many missions are available and try them. It would also help if the GUI allowed to select a mission without going through the demon screen and manualy typing the name but that’s another subject.

**Comment by smcameron** [comment]
> I also think it would be better if misson scripts were easy to differentiate from other scripts.
...
> It would also help if the GUI allowed to select a mission without going through the demon screen

If you run MAINMENU.LUA from the demon screen, a menu is presented on the MAIN VIEW showing the available mission scripts.

Currently there are only 5, and some of dubious quality.

TRAINING-MISSION-1 -- pretty basic, just has you run around and dock with 4 starbases.
SAVING-PLANET-ERPH - destroy 5 zarkon ships to help planet erph
SPACEPOX - recover medicine before spacepox kills all crewmembers of a starbase
KALI - Don't remember how far I got on this one, I think it's not very good.
DEMOLISHER - Not completely finished, but it does have a cool big-giant ship with a special door you have to figure out how to open.

Any help making more mission scripts would be greatly appreciated.

**Comment by MCMic** [comment]
Oh ok that mainmenu is a good feature. It should be advertized for new players.

> Any help making more mission scripts would be greatly appreciated.

I’ll wait before I’ve played some of the existing ones before going that road.

Closing this ticket since luascripts are installed and there is a menu for missions.
