### ISSUE TITLE
Missing joystick functions

### ISSUE THREAD

**Issue by MCMic** [smcameron/space-nerds-in-space#183]
I bought a second hand joystick today and was able to test joystick support.

I’ll probably send a patch to add support for this one in joystick_config.txt.

But as I configured it I noticed I’m missing the following features:

- [x] Map an axis to warp control (this joystick has a split gas control so I wanted to assign the left part to throttle and the right part to warp)
- [x] Map a button to lights
- [x] Map a button to missiles 
- [x] In the same way I feel like we should have a way to send missiles with mouse buttons 3/4/5 (3 is usually mouse wheel click, 4/5 are prev/next button on the side of my mouse)
- [x] Invert an axis. In my case it is only needed for weapon controls vertical axis, and "ctrl+I" does not work for the joystick.
- [x] Map the weapon wavelength to an axis 
- [x] Map the weapon wavelength to buttons

Maybe a generic solution should be found for assigning the same thing either to buttons or an axis. (would fix warp control and help with wavelength)

**Comment by MCMic** [comment]
[0001-Add-joystick-support-for-lights-control.patch.txt](https://github.com/smcameron/space-nerds-in-space/files/2796345/0001-Add-joystick-support-for-lights-control.patch.txt)
[0002-Add-joystick-support-for-firing-missiles.patch.txt](https://github.com/smcameron/space-nerds-in-space/files/2796347/0002-Add-joystick-support-for-firing-missiles.patch.txt)
[0003-Add-joystick-support-for-weapons-wavelength-control.patch.txt](https://github.com/smcameron/space-nerds-in-space/files/2796348/0003-Add-joystick-support-for-weapons-wavelength-control.patch.txt)

Here are patches for the easy ones.
I failed to add wavelength control from an axis, I’m not sure why since the code of snis_slider_set_input and snis_slider_nudge seems quite close.
Because of this I did not try to add warp control through an axis either.

**Comment by smcameron** [comment]
Thanks for reporting these, and for the patches.

You can invert an axis in the joystick config file.  From the comments in share/snis/joystick_config.txt:

```
# Here are examples of mapping a mode + button or mode + axis to a function:
#
#  mode 0 button 1 phaser               # map mode 0 button 1 to phaser function
#  mode 1 axis 2 yaw                    # map mode 1 axis 2 to yaw function
#  mode 1 invert axis 3 roll            # map mode 1 axis 3 to roll function and invert the axis
#
```

**Comment by smcameron** [comment]
Applied your patches.  Thanks.

* d1a55e087f96afc65dcfc8219056c2bd3e15cb5d
* d0a6c2f02aba35867562d93bc88d8540673482c8
* 2fe0a1c9376045bd8b05afa96a3bde11372fad0e

Also documented the joystick config file "functions" or keywords or whatever I should call them.

* 199881159c50809b58f1b1f47034c4d04bccdb91

**Comment by MCMic** [comment]
Thanks for the information, the invert keyword works fine :-)

Hmm, it sounds to me like XJOYSTICK_THRESHOLD_FINE/YJOYSTICK_THRESHOLD_FINE are not working, as they are equal to JOYSTICK_DEADZONE.
I’d vote for changing JOYSTICK_DEADZONE to be 3000 instead of 6000, what do you think?

The other problem is when an axis is mapped to a slider like throttle (or warp with my incomming patch), the deadzone system prevents from setting the slider to 50%, there is a jump from 50% - deadzone to 50% + deadzone.
So I think the deadzone system should be deactivated for throttle/warp/wavelength axis functions.

**Comment by smcameron** [comment]
Hmm, glancing at the code, regarding the deadzone vs. fine threshold, it sure looks like you're right (I didn't actually try it out myself today to verify though).  Try it and see how it is.

Hmm.  Wonder if the deadzone should have a default value and be optionally adjustable per axis via the config file somehow.

**Comment by smcameron** [comment]
> I failed to add wavelength control from an axis, I’m not sure why since the code of snis_slider_set_input and snis_slider_nudge seems quite close.

Maybe you want snis_slider_poke_input().

snis_slider_set_input just sets the visual marker for the input.  snis_slider_poke_input() sets the visual marker and triggers the ->clicked() callback of the slider.

**Comment by MCMic** [comment]
Testing a bit, it sure feels like deadzone and fine thresold should be configurable by joystick or even by axis. With my joystick I’d need a really small deadzone while I understand something like a gamepad would need a bigger one.
And that would allow to set no deadzone on axis assigned to sliders.

> snis_slider_set_input just sets the visual marker for the input. snis_slider_poke_input() sets the visual marker and triggers the ->clicked() callback of the slider.

For warp it works if I use snis_slider_set_input and then call do_warpdrive. I did that because throttle is doing something similar. Is calling snis_slider_poke_input instead cleaner?

**Comment by smcameron** [comment]
> For warp it works if I use snis_slider_set_input and then call do_warpdrive. I did that because throttle is doing something similar. Is calling snis_slider_poke_input instead cleaner?

Hmm, I don't know.  Neither seems especially clean or dirty. :) My gut says snis_slider_poke_input is a little cleaner since that triggers the same code path that clicking on the slider with the mouse triggers (going through the slider's ->clicked() function pointer.  The throttle slider's ->clicked() function pointer points to do_throttle() so both approaches end up doing the same thing.  Probably the throttle one should use snis_slider_poke_input() too.   But, either is acceptable to me.  I might go back and audit and change them all to snis_slider_poke_input() as appropriate at some point if it still seems like a good idea to me.

**Comment by smcameron** [comment]
> Testing a bit, it sure feels like deadzone and fine thresold should be configurable by joystick or even by axis. With my joystick I’d need a really small deadzone while I understand something like a gamepad would need a bigger one.

Alright, I'll think about doing that then (unless you want to take a stab at it.  I expect the parsing of the config file is not much fun... probably a bunch of sscanf() calls, iirc.) Not today though.  Maybe next week.

**Comment by MCMic** [comment]
Actually I think fine threshold is working, XJOYSTICK_THRESHOLD_FINE is just a duplicate of JOYSTICK_DEADZONE and a joystick event under 6000 kind of get ignored twice. So the code is not broken, just redundant.

I think I will try and add a deadzone setting per axis which defaults to 6000. And let the fine system be as it is for now.

**Comment by smcameron** [comment]
If you look at do_joystick_pitch(), you can see that it's trying to do different things based on the YJOYSTICK_THRESHOLD_FINE value... that is, it's packing different values into the pitch request 
packet for a fine or coarse pitch adjustment.  (see  https://github.com/smcameron/space-nerds-in-space/blob/master/snis-protocol.html#L509 ) However, I don't see how do_joystick_pitch() would ever get called with value between -YJOYSTICK_THRESHOLD_FINE and +YJOYSTICK_THRESHOLD_FINE because of this:

```
 3956                 /* Fire off joystick axis callbacks registered via set_joystick_axis_fn() */
 3957                 for (i = 0; i < ARRAYSIZE(jss[j].axis); i++)
 3958                         if (jss[j].axis[i] < -JOYSTICK_DEADZONE ||
 3959                                 jss[j].axis[i] > JOYSTICK_DEADZONE)
 3960                                 joystick_axis(joystick_cfg, NULL, displaymode, j, i, jss[j].axis[i]);
```

So... I don't think it's correct as it stands with deadzone and fine both being 6000.

**Comment by MCMic** [comment]
[0001-Add-joystick-axis-function-for-warp-control.patch.txt](https://github.com/smcameron/space-nerds-in-space/files/2797923/0001-Add-joystick-axis-function-for-warp-control.patch.txt)
[0002-Use-snis_slider_poke_input-for-joystick-throttle-and.patch.txt](https://github.com/smcameron/space-nerds-in-space/files/2797924/0002-Use-snis_slider_poke_input-for-joystick-throttle-and.patch.txt)
[0003-Add-joystick-axis-support-for-wavelength-control.patch.txt](https://github.com/smcameron/space-nerds-in-space/files/2797932/0003-Add-joystick-axis-support-for-wavelength-control.patch.txt)
[0004-Avoid-code-duplication-and-magic-numbers-in-joystick.patch.txt](https://github.com/smcameron/space-nerds-in-space/files/2797926/0004-Avoid-code-duplication-and-magic-numbers-in-joystick.patch.txt)
[0005-Add-warp-and-weapons-wavelength-to-documentation.patch.txt](https://github.com/smcameron/space-nerds-in-space/files/2797927/0005-Add-warp-and-weapons-wavelength-to-documentation.patch.txt)
[0006-Add-joystick-config-for-Logitech-G-Saitek-Cyborg-FLY.patch.txt](https://github.com/smcameron/space-nerds-in-space/files/2797928/0006-Add-joystick-config-for-Logitech-G-Saitek-Cyborg-FLY.patch.txt)

Here are patches for control by axis for warp and wavelength. I switched to snis_slider_poke_input and wrote a helper to avoid having the same code three times for all three sliders.
The last patch is my current configuration for my joystick, using the features from the other patches.
I sliced everything down as I added them but you can stash commits together if that feels like too much details.

**Comment by smcameron** [comment]
Ah, that explains it.  Who wrote this crap? :)

**Comment by MCMic** [comment]
[0001-Add-support-for-axis-specific-deadzone-setting.patch.txt](https://github.com/smcameron/space-nerds-in-space/files/2798150/0001-Add-support-for-axis-specific-deadzone-setting.patch.txt)

In the end it was quite easy to add per-axis deadzone setting, I took the invert setting as example.
Setting deadzone to 0 for sliders fix the problem. There is still a weird pause at mid-slider but joystick_test shows me that it’s just a problem on my joystick which sends 0 for quite a large zone in the middle.

**Comment by smcameron** [comment]
Awesome patches, thanks.  I applied them all.

BTW, in future please add a "Signed-off-by" line to the patch description as described in item 12 at the bottom of this page: https://github.com/smcameron/space-nerds-in-space/blob/master/CONTRIBUTING.md

Also, you might want to run your patches through checkpatch.pl (not that it found anything other than the missing Signed-off-by line), e.g.  "git diff | ./checkpatch.pl -"

Thanks again.

**Comment by MCMic** [comment]
[0001-Add-config-for-Thrustmaster-T.Flight-Stick-X.patch.txt](https://github.com/smcameron/space-nerds-in-space/files/2803991/0001-Add-config-for-Thrustmaster-T.Flight-Stick-X.patch.txt)
Here is a configuration for the joystick of a friend we used for weapons.
I also mapped damcon, and navigation even if there is not enough buttons/axis to completely replace the keyboard on this one.

**Comment by smcameron** [comment]
Thanks, applied.

How are you finding the game?  I don't get a lot of feedback... not many people play with this game.

**Comment by MCMic** [comment]
@smcameron I posted the feedback here: https://forum.freegamedev.net/viewtopic.php?f=22&t=3710&p=82938#p82931

**Comment by smcameron** [comment]
Awesome, thanks!

**Comment by MCMic** [comment]
> In the same way I feel like we should have a way to send missiles with mouse buttons 3/4/5 (3 is usually mouse wheel click, 4/5 are prev/next button on the side of my mouse)

@smcameron Regarding this, what do you think?

I think I found where the change would be, it’s in `main_da_button_release`, currently it tests for 1 and 3 which are left and right buttons.
Middle clic is 2 and the other ones 4 and 5.
On my mouse button 4 seems appropriate for missiles, but on a usual mouse with no extra button I guess middle clic would be better?
Should I just bind both?

**Comment by MCMic** [comment]
[0001-Bind-missile-to-mouse-buttons-as-well.patch.txt](https://github.com/smcameron/space-nerds-in-space/files/2824955/0001-Bind-missile-to-mouse-buttons-as-well.patch.txt)

Here it is

**Comment by smcameron** [comment]
Thanks, applied.

**Comment by MCMic** [comment]
Thanks
