### ISSUE TITLE
[Lua API] money transfer

### ISSUE THREAD

**Issue by MCMic** [smcameron/space-nerds-in-space#186]
Hello,

I would need a way to add money in the player wallet when the mission is successful.
It seems the current API allows for checking the current wallet content but not to add/take money to/from it.

I could give cargo instead but it feels indirect.

**Comment by smcameron** [comment]
Done. 5f008afb9f84b0ce42e99e1eca2515817a45f14c

**Comment by MCMic** [comment]
Thanks, seems to work.
