### ISSUE TITLE
When reversing throttle we still see propulsion at the back of the ship

### ISSUE THREAD

**Issue by MCMic** [smcameron/space-nerds-in-space#187]
When the pilot use the "R" to go backwards, the game still applies a particle propulsion effect to the back of the ship instead of the front (Where I guess there is a second reactor, in order to go backwards?).

This can be troubling especially to the weapon guy.

**Comment by smcameron** [comment]
Ok.  Turned off the thrust flares while reversing: 3d8c7be4d6936d40a0cd87dd1f33ea6267cd998e
Also limited ship speed while reversing: 93cc84d7b168d9a3740e6d037a422d091aded279
The max reverse player ship speed is tweakable via the demon console, as is the max forward player ship speed.

**Comment by MCMic** [comment]
Thanks, that was quick
