### ISSUE TITLE
Along with OpenGL, support OpenGLES

### ISSUE THREAD

**Issue by kwadroke** [smcameron/space-nerds-in-space#19]
Devices like the Raspberry Pi, Android phones and devices,  Beagleboards and other embedded systems do not support full OpenGL. Please add support for OpenGLES for those and other systems.

**Comment by smcameron** [comment]
Thanks to @kuroneko there is now support for OpenGLES.

Compile via "make USE_GLES=1"

The following commits (listed newest to oldest) add support for OpenGLES:

* 93e6d58c1f68b173e01bd6f70db2aa22ecf0e5d8 Invalidate correct FBO attachments
* f98a25476d88c50957eed32713bfa8ca54573f9e Fix incorrect target for glFramebufferRenderbuffer command.
* 7740352735ece16af1a22411f0b2862cbb8e7adf Small tweak to SMAA shader handling.
* 3f84902d157da8d633c008354b0af6f4005a6d2b run the shaders through glslangValidator and fix errors.
* 1addb211f6ca97e86ecb5cc7f6f67d6b295c5188 discard FBOs once blended.
* 4caa04c7e11d23ab8b4ecf66a9062492ab86dd83 graph_dev_*: remove duplicated form of ARRAYSIZE macro
* 9c5bf87881ba910d3545370261454f786ede31dd graph_dev_opengl: match resize_fbo_if_needed to GLES version.
* 1cc315f206473faef32365c41aba11b977beb53d graph_dev_opengl.c: remove redundant buffer bind.
* 15091fe6e3f6f3c29a467de3ca2aa664d19537fb graph_dev_opengl.c: Fix bad clear color for FBO targets
* 97378281b02ce5b62a01ce366de15f848cea3178 Fix broken texture name reuse in the GLES driver
* 156edbb15cd405ee013ae1443a2bea667851730e Implement the GLES2 renderer
* d7299d8de2c4f99490d800ca2d684dfca7a202b0 Make it build on raspberry pi
* 0b1162f90f870dc4b2e4fe46699a3539c3333195 snis_xwindows_hacks: don't abuse implicit argument lists
* a8b49a2e52751441934efe7a30c86b750bd4792c snis_client: don't call glFinish.
* 591291bd7b7b0cd6234f3bd07103cc3be7f2bab3 Update SMAA shader for OpenGL renderer
* d75e629332b78ae3e30b5cf8489a93d63523517d graph_dev_opengl.c: fix colourspace for cubemap uploads.
* 9579874b58472c3e830fb0eda491bdd93d4b4b5d graph_dev_opengl.c: now that we use VAOs, remove redundant attribute unbinding.
* ff88e5399ab86ffe38029445a3c12dfde3c0e2cf graph_dev_opengl.c: move enablement of seamless cubemaps to renderer setup.
* 0924d52a920f2eeb8f8435837ef364cb79e36797 Fix incorrect error message on incomplete framebuffer
* 7c2f47f6c1d37c3756f0eb54f96558e1b156400a Instrument OpenGL driver for profiling
* fe4720cba044bb1aa7f4412c42720ff04254dbed Change intent of 3d "line" buffer
* 966fb7121af83b412fa932612e2479e81ec82d5e graph_dev_opengl: switch from glDrawBuffer to glDrawBuffers
* 4a837332c3f3453f10e1b3e6a72c5a7366ec678d Fix broken texture name re-use
* 6c5bc6efeb13004d22d840100d2fd54e8d6a2fc1 Push the OpenGL renderer up to GL 3.2 Core
* 7d285bd6aa3596b3506d5dc8c0e2920fc6cfafbd Elide duplicated activate_shader calls
* c5a5f5de7429fb315fee5edc23e5b51484b5297e Use common hook to set active shader (program)
* 1ad7b8419313f37ce1bd519f63d01b5324aa4c32 Remove redundant/unecessary binding of Program 0.
* 339e4e3e3068aca19c3ab9f08304fe98efbf13b2 Add hook to make shader compilation barf if a shader files.
* f324fbc420d0d1e011ce04da0ff59443d9286a46 Pass the asset_dir to graph_dev_setup, not the shader path
* d2c704569de751a77d477e031de62267ecbdb5f2 Move GL context creation into graph_dev
* 2c2a94c190a14ca5bc9c6d9f569c39789e5e0777 Update .gitignore
