### ISSUE TITLE
Passengers survive the crash

### ISSUE THREAD

**Issue by MCMic** [smcameron/space-nerds-in-space#190]
When crashing the ship, the cargo is lost, but the passengers are miraculously alive after respawning.

This feels a bit weird (even if respawning in itself is cheating death somehow).

I also feel like we should have a way to float passengers in outer space, even if it is not nice to do so.

**Comment by smcameron** [comment]
Could you test this patch which should clear passengers on respawn (but not on docking)?

[clear-passengers-on-respawn.txt](https://github.com/smcameron/space-nerds-in-space/files/2829793/clear-passengers-on-respawn.txt)

Spacing passengers probably requires some 3d model for the floating passenger carcass, eh?

**Comment by MCMic** [comment]
Seems to work

**Comment by MCMic** [comment]
> Spacing passengers probably requires some 3d model for the floating passenger carcass, eh?

Yeah that would be "cool".

**Comment by MCMic** [comment]
https://opengameart.org/content/astronaut-1 maybe this one?

**Comment by smcameron** [comment]
Maybe... I don't know if I want to go down this road.  You're forcing me to think about the scale of all the ships, etc.  I suspect once I do think about that, those 640 texture mapped triangle astronauts will be rendered down to a few pixels most of the time.  Seems like a long way to go for a mechanic that (so far) seems like almost a joke.   Is there more to spacing passengers than just watching them float off?  How do you imagine it working?  I'd expect you'd need to be able to pick up spaced passengers, dead or alive, then carry around corpses as well as passengers.  And what else can you do?  Might be good.... or might be a can of worms.  What do you think?

**Comment by MCMic** [comment]
I’m not sure, it was kind of for the joke, because in the lua mission script I’m putting together the passenger could get too anoying for the crew to endure, and I guess that would have been a "fun" way to fail the mission. After all, there is a button for ejecting the warp core, which I’m not sure if it’s ever a good idea.

I would have put in a basic mechanic based on the one to eject cargo, which does about the same thing but with an other sprite, and bodies would not be «minable». I would also expect those to have short life time to not add useless objects to the solarsystem for too long.

I stopped at «Cute little lowpoly astronaut» and did not see it was 640 tris. It may not be lowpoly enough for our usecase, basically anything that looks ok as wireframe on the science screen would be ok I guess.

This is obviously not high priority, just felt like it was a missing part of the passenger system.

**Comment by smcameron** [comment]
640 triangles isn't really very many.  I was mostly just wondering if, at proper scale, the little guy would ever occupy more than a few pixels on the screen.  640 tris is kind of a lot *for a few pixels*, but it's not a lot in the scheme of things.  I'll think about it, maybe I'll do something with it.

As for the warp core ejection, I added this for the obvious Star Trek reference -- of course you should be able to eject the warp core -- and for the (unfinished) DEMOLISHER mission, my idea was that the way to destroy the demolisher ship was to go inside it and overheat the warp core, then eject the warp core and run away.  The overheated warp core would explode, demolishing the demolisher. I haven't got that last bit about demolishing the demolisher implemented yet though.

**Comment by MCMic** [comment]
> Could you test this patch which should clear passengers on respawn (but not on docking)?
> 
> [clear-passengers-on-respawn.txt](https://github.com/smcameron/space-nerds-in-space/files/2829793/clear-passengers-on-respawn.txt)

This was never merged in it seems.

**Comment by MCMic** [comment]
> 640 triangles isn't really very many. I was mostly just wondering if, at proper scale, the little guy would ever occupy more than a few pixels on the screen. 640 tris is kind of a lot _for a few pixels_, but it's not a lot in the scheme of things. I'll think about it, maybe I'll do something with it.

Thinking about that, even if it almost never appears on main screen, having the model will still be useful for the science station scanner. And I guess the mining bot camera feed if we are able to "mine" them…

**Comment by smcameron** [comment]
> > Could you test this patch which should clear passengers on respawn (but not on docking)?
> > [clear-passengers-on-respawn.txt](https://github.com/smcameron/space-nerds-in-space/files/2829793/clear-passengers-on-respawn.txt)
> 
> This was never merged in it seems.

Thanks. Merged as 471c91fb405598dad639904717f0c8df380134f4
