### ISSUE TITLE
Start lua scripts from outside

### ISSUE THREAD

**Issue by MCMic** [smcameron/space-nerds-in-space#193]
Hello,

I have KDE connect setup which allows me to start commands on my computer from my phone.
Using the fifo for natural language that would allow me to start computer commands, but I would be interested in starting lua scripts, mainly for mainmenu and regenerate.

Is that already possible somehow?
Would that hard to add if not?

**Comment by smcameron** [comment]
It wouldn't be too hard.  Very similar to the natural language fifo setup, use a thread to monitor a fifo and dump whatever text comes in through construct_demon_command() function on the client.

You could use netcat to allow feeding the fifo remotely, similar to what's described here: https://smcameron.github.io/space-nerds-in-space/#speech-recognition   under "android based speech recognition".

**Comment by smcameron** [comment]
Ok, now there is a fifo /tmp/snis-demon-fifo, into which you can send whatever you like and it will be run as if typed on the demon screen.

**Comment by MCMic** [comment]
![kdeconnect](https://user-images.githubusercontent.com/106382/52743562-99218e80-2fda-11e9-801d-140dff37f0fe.png)

Awesome, I can launch all this from my phone now :-)

Regarding main menu, I was a bit surprised it does not have the dismiss button like the mission text does, once I start main menu it seems I have to start one of the missions and can’t go back.

**Comment by smcameron** [comment]
>Regarding main menu, I was a bit surprised it does not have the dismiss button

Ok, I added a dismiss button, and a button on the main menu to allow regenerating the universe.
