### ISSUE TITLE
make install-assets ?

### ISSUE THREAD

**Issue by MCMic** [smcameron/space-nerds-in-space#200]
Hello,

Since make install does not install extra assets from update-assets, the only easy way we have to install those is to copy the whole share/snis folder.
But this brings model sources like .scad, .xcf and .blend as well which we do not need.

Would it be possible to add an install-assets target which copies the assets fetched from update-assets to DESTDIR/share/snis/ ?

**Comment by smcameron** [comment]
How about:

make update-assets DESTDIR=whatever
make check-assets DESTDIR=whatever

Try the attached patch.

[teach-snis-update-assets-about-DESTDIR.txt](https://github.com/smcameron/space-nerds-in-space/files/2884903/teach-snis-update-assets-about-DESTDIR.txt)

**Comment by MCMic** [comment]
Does not really work for my usecase (which is building the AUR package with all the data), because I need to run `make update-assets` in source folder so that `make install` finds the models (otherwise they get compiled from scad files).

I need to be able to use `make update-assets` for the download, then `make install`, then something else to copy the missing assets.

The current PKGBUILD does:
```
build() {
  cd "$srcdir/$pkgname"
  make PREFIX="/usr"
  make update-assets
}

package() {
  cd "$srcdir/$pkgname"
  mkdir "$pkgdir/usr"
  make PREFIX="/usr" DESTDIR="$pkgdir" install
  rm "$pkgdir/usr/share/applications/mimeinfo.cache"
}
```

And the additional assets are missing from the resulting package.
The idea was to add something after the call to make install that would copy the assets.

**Comment by smcameron** [comment]
Then send me a patch that does what you want, because what you want is specific to your packaging.

**Comment by smcameron** [comment]
To do what you want, I believe "make update-assets" would have to record whatever it did somehow.  This is starting to get a little bit on the nuts side.

**Comment by smcameron** [comment]
I went ahead and committed that patch, but without the Makefile part, so make update-assets DESTDIR=blah doesn't do anything different, but if you run util/snis_update_assets.sh --destdir=blah, that will do something different.

**Comment by smcameron** [comment]
Here's an idea.  Get rid of "make update-assets" altogether.  Instead, snis_client directly populates ~/.space-nerds-in-space/share/snis/ by opening a socket to www.spacenerdsinspace.com and do what make update-assets does at runtime.

**Comment by MCMic** [comment]
> Here's an idea. Get rid of "make update-assets" altogether. Instead, snis_client directly populates ~/.space-nerds-in-space/share/snis/ by opening a socket to [www.spacenerdsinspace.com](http://www.spacenerdsinspace.com) and do what make update-assets does at runtime.

Sounds like a bad idea to bind the use of the client to a webserver that may be down in the future. Having the clients fetch data from the game server may make sense, but from an internet source that is weird.

I’ll see if I can implement the install-assets target I had in mind.

> To do what you want, I believe "make update-assets" would have to record whatever it did somehow. 

I thought the list of the downloaded files were already saved in a manifest file.

**Comment by smcameron** [comment]
Yeah, they are in the manifest file, though snis_update_assets.sh removes that file when it's done.

**Comment by smcameron** [comment]
Alright see if this patch is more to your liking.  I updated util/snis_update_assets to be able to do a local copy.

[add-install-assets-target.txt](https://github.com/smcameron/space-nerds-in-space/files/2885397/add-install-assets-target.txt)

**Comment by smcameron** [comment]
New version of patch to accomodate 0c84dffb27a5f4bee1b44987c118a25fa53bec40

[add-install-assets-target-v2.txt](https://github.com/smcameron/space-nerds-in-space/files/2885602/add-install-assets-target-v2.txt)

**Comment by MCMic** [comment]
Thanks!

There’s a typo **utile** instead of **util**
Also it would be better if it took PREFIX into account as well, otherwise I end up with:
```
  make PREFIX="/usr" DESTDIR="$pkgdir" install
  make DESTDIR="$pkgdir/usr" install-assets
```
Which looks a bit inconsistent.

Otherwise it works fine!

**Comment by smcameron** [comment]
Alright, how's this?
[add-install-assets-target-v3.txt](https://github.com/smcameron/space-nerds-in-space/files/2885789/add-install-assets-target-v3.txt)

**Comment by MCMic** [comment]
Perfect :-)

**Comment by smcameron** [comment]
Committed as a1c66393b3767fddae602afe548364cfd62cee9a
