### ISSUE TITLE
Make install is broken (textured-cubemap-and-lit-per-pixel.shader not found)

### ISSUE THREAD

**Issue by MCMic** [smcameron/space-nerds-in-space#212]
`make[1]: ***  Aucune règle pour fabriquer la cible « share/snis/shader/textured-cubemap-and-lit-per-pixel.shader », nécessaire pour « install ». Arrêt.`

Sorry for the french, but basically `share/snis/shader/textured-cubemap-and-lit-per-pixel.shader` has been removed but is still listed by `make install` I suppose.

**Comment by smcameron** [comment]
Thanks! Should be fixed by: 9a0e0e0261f420d60f82ebb31007db3ed3989a8d

I also noticed make install can trigger re-building SCAD files.... :(

**Comment by MCMic** [comment]
Thanks
