### ISSUE TITLE
Crash of science station

### ISSUE THREAD

**Issue by MCMic** [smcameron/space-nerds-in-space#217]
Sorry, I do not have a lot of info on this one, but while playing royal wedding, just after getting out of warp in a nebula with lots of asteroids, the science station crashed. Starting snis_client again and connecting worked fine.

**Comment by smcameron** [comment]
I think I might have seen this once before.  Running with ulimit -c unlimited might help to get a core file.  But I do not know how to duplicate this reliably (I've only seen it once maybe 2 months ago.)

**Comment by smcameron** [comment]
I'm suspecting something maybe related to o->entity being NULL unexpectedly, or maybe the mesh associated with o->entity being NULL, but this is only a hunch.

**Comment by smcameron** [comment]
I think this one is too old, and lacks enough information to proceed with any action, so I am closing it.
