### ISSUE TITLE
Missing files in make install

### ISSUE THREAD

**Issue by MCMic** [smcameron/space-nerds-in-space#218]
I can see in the log:

> Unable to load texture '/usr/share/snis/textures/lens_flare_ghost.png': Failed to open '/usr/share/snis/textures/lens_flare_ghost.png': No such file or directory
> Failed to load texture from '/usr/share/snis/textures/lens_flare_ghost.png'
> Unable to load texture '/usr/share/snis/textures/lens_flare_halo.png': Failed to open '/usr/share/snis/textures/lens_flare_halo.png': No such file or directory
> Failed to load texture from '/usr/share/snis/textures/lens_flare_halo.png'
> Unable to load texture '/usr/share/snis/textures/anamorphic_flare.png': Failed to open '/usr/share/snis/textures/anamorphic_flare.png': No such file or directory
> Failed to load texture from '/usr/share/snis/textures/anamorphic_flare.png'

They seem to be there in the git so I guess they are missing from make install?

Am I right to assume the black box artefact we got ingame in some lights would come from this?

**Comment by smcameron** [comment]
> Am I right to assume the black box artefact we got ingame in some lights would come from this?

Yeah, that seems possible and likely.  It was supposed to have looked something like the pic in #210  You can turn off lens flare on the demon screen by typing "set lens_flare = 0" and if that makes the black box artifact go away, then that would confirm your suspicions.

**Comment by smcameron** [comment]
Should be fixed by 3ba89ab1f7a888d313f748935108e28bf6add23b

**Comment by MCMic** [comment]
Comparing installed share folder with git share folder to check this, I see that interactive_fiction.lua is in a lib subfolder in the git, while once installed it’s directly in MISSONS folder, not sure if this can cause trouble for file inclusion or not?

Also, these files are not installed, not clear if this is on purpose:
- share/snis/luascripts/TEST: TESTCIPHER.LUA
- share/snis/luascripts/TEST: TESTDAMAGE.LUA
- share/snis/luascripts/TEST: TESTTORP.LUA
- share/snis/luascripts/UTIL: LS.LUA
- share/snis/luascripts/UTIL: SETFACTION.LUA
- share/snis/luascripts/UTIL: SET_SB_FACTION_MASK.LUA
- share/snis/sounds: quindar-intro.ogg
- share/snis/sounds: quindar-outro.ogg

**Comment by smcameron** [comment]
Thanks.  I need to get some kind of automated testing around this at some point.

**Comment by smcameron** [comment]
Hmm, "make DESTDIR=/tmp/testinstall" seems to rebuild some of the openscad models.  It shouldn't need to.

```
  OPENSCAD share/snis/models/dragonhawk.scad
Could not initialize localization.
  OPENSCAD share/snis/models/skorpio.scad
Could not initialize localization.
  OPENSCAD share/snis/models/heading_indicator_tail.scad
Could not initialize localization.
  OPENSCAD share/snis/models/warpgate.scad
Could not initialize localization.
  OPENSCAD share/snis/models/space_monster_torso.scad
Could not initialize localization.
  OPENSCAD share/snis/models/space_monster_tentacle_segment.scad
Could not initialize localization.
  OPENSCAD share/snis/models/cylinder.scad
Could not initialize localization.
  OPENSCAD share/snis/models/missile.scad
Could not initialize localization.
```

**Comment by smcameron** [comment]
I think this should fix the missing lua test, utils and missing sound files: d6a657d29a136f27634d065c30d555562eae838c

**Comment by MCMic** [comment]
@smcameron What about `interactive_fiction.lua`, is it on purpose that it’s in a lib subfolder in git but not in installation result? won’t that cause problems to scripts?

**Comment by smcameron** [comment]
Oh, yeah, missed that.  Thanks for reminding me. This should do it: e17167d77202fc10bee52ed8cdcafa7439bbb4d1

**Comment by MCMic** [comment]
Thanks
