### ISSUE TITLE
There are two states of empty cargo bay

### ISSUE THREAD

**Issue by MCMic** [smcameron/space-nerds-in-space#219]
At some point I wanted to empty all cargo bays, and some were saying «cargo bay is empty» when trying to eject while they did not appear that way in the manifest.
Looking closer I saw that they contains 0 tons of something.

So a cargo bay can be stated as empty or as containing 0 unit of something, which is the same thing, it should always say empty in my opinion.

**Comment by smcameron** [comment]
This may be a rounding error.  Might have 0.01 tons, but claims "0".  In any case it sounds like a bug.  Thanks.

**Comment by MCMic** [comment]
We used the mining bot but on crates only as far as I remember. The condition for stating "empty" and refusing to eject should be the same one.

**Comment by smcameron** [comment]
Hmm... the code looks like:

```
        if (ship->tsd.ship.cargo[cargobay].contents.item == -1 ||
                        ship->tsd.ship.cargo[cargobay].contents.qty <= 0.0)
                goto empty_cargo_bay;
```
So that doesn't look like a rounding error.  The exact message you get is "EMPTY CARGO BAY" in this case.

/inventory can say "CARGO BAY X: EMPTY"...

```
                if (ccc->item == -1) {
                        send_comms_packet(NULL, name, ch, "    CARGO BAY %d: ** EMPTY **", i);
```

So this leads me to think that you somehow had a negative or zero quantity of some actual cargo -- qty was 0.0 or negative, and item was not -1.  Pretty cool, shades of "no tea", from hitchhikers guide to the galaxy.  I kind of remember that for awhile that maybe you used to be able to sell negative amounts of stuff (and thus get the stuff, kind of like "no tea" in HHGG) but I'm pretty sure I fixed those kinds of shenanigans.

**Comment by smcameron** [comment]
> The condition for stating "empty" and refusing to eject should be the same one.

Yes, of course  The question I have though is how qty == 0 and item != -1.  That should not happen.

**Comment by MCMic** [comment]
We did not sell/trade as far as I remember, only miningbot/tractor on crates and some ejecting. Could the mining bot store 0 of something from a crate?

**Comment by MCMic** [comment]
Also some regenerate and start/win/loss of mission scripts, if that may mess cargo somehow.

**Comment by smcameron** [comment]
Ok, I think I see how a degenerate cargo with qty == 0 can be generated, in add_ship()...

```
        for (cb = 0; cb < go[i].tsd.ship.ncargo_bays; cb++) {
                int item = commodity_sample();
                float qty = (float) snis_randn(100);
                go[i].tsd.ship.cargo[cb].contents.item = item;
                go[i].tsd.ship.cargo[cb].contents.qty = qty;
```

snis_randn(x) can return 0.

**Comment by smcameron** [comment]
I don't think the mining bot will change the quantity on a crate, so if the quantity was wrong, it's not the mining bot doing it.  (Not quite so sure about actual mining activity on asteroids though. Could still be problems there) Ok, I think these might help with the situation you encountered:

* 251dccb6dc5153a222aacd01cef99050a79dff0b  Fix generation of zero quantity cargo contents 
* 47fd700f5707649f3491c887880fa3dbe8342fca  When checking for empty cargo bays, always check item AND quantity

**Comment by MCMic** [comment]
I guess we can close this then? (It’s hard to test anyway… I will reopen it if it happens again)
