### ISSUE TITLE
Players cannot reliably scan their own ship with SCIENCE

### ISSUE THREAD

**Issue by smcameron** [smcameron/space-nerds-in-space#231]
On the SCIENCE screen, you cannot select your own ship.  This was by design, but I'm not sure it's the right choice.

On COMMS, you can aim SCIENCE at your own ship.  If your ship is named PEAQUOD, you can type "/computer select peaquod", and you will be able to scan your own ship, and see a few attributes (e.g. find out what faction you are.)  Sometimes it instantly de-selects though (not sure why).  Also it shows up as type UNKNOWN, which seems wrong.

Is there any reason you shouldn't be able to scan yourself?  I can't really think of one, and it might conceivably open up some interesting game mechanics as well.

Also, I suspect if you cannot really scan your own ship, you probably can't scan other player's ships either, which you should definitely be able to do that.  Edit: It turns out you can scan other players ships.  However somethings don't seem correct (e.g. LIFEFORMS: 0, no weapons shown.)

**Comment by MCMic** [comment]
Not sure if it makes sense to scan ourselves, I would expect this kind of info to show up in manifest or engineering screen, as those are more oriented towards our ship, while science screen is about what's out there.

**Comment by smcameron** [comment]
* f705375dc811730cdda8e5717bf36f2ee82b6163  Allow self-selection on SCIENCE screen 
* 3b2770e6d311cff8433e5e689bd7bbd045126bc9 Track player ship lifeform count
* 2d51e6b2c0c16ae1e024e6dfdeb56d5039efbe9a  Improve SCIENCE details for player ships
