### ISSUE TITLE
Have some feedback on money changes when disembarking passengers

### ISSUE THREAD

**Issue by MCMic** [smcameron/space-nerds-in-space#244]
When ejecting/disembarking passengers, you earn money for disembarking and you lose money for ejecting at the wrong station.

This should be explicit.

See https://forum.freegamedev.net/viewtopic.php?f=22&t=3710&start=300#p82874

**Comment by smcameron** [comment]
Good idea.  Thanks.

**Comment by smcameron** [comment]
This should make it a bit clearer: 73f8825391985fff20c1e122351d067be0934a41

**Comment by MCMic** [comment]
Seems to work when ejecting but not when disembarking?

![Screenshot_20200220_211212](https://user-images.githubusercontent.com/106382/74977984-0e187700-542c-11ea-803f-04de85040d1f.png)

I guess you forgot to add the explicit output to `npc_menu_item_disembark_passengers`.

**Comment by smcameron** [comment]
Oh, so I did.  Thanks.

* 36acfe4b342b8686eda5c798990b41caa86a7149  Mention fares collected in npc_menu_item_disembark_passengers()
