### ISSUE TITLE
update_multiverse_bridge_count crashes if no multiverse server is in use

### ISSUE THREAD

**Issue by CapnRobberts** [smcameron/space-nerds-in-space#245]
update_multiverse_bridge_count blindly uses the global multiverse_server even if it's set to NULL.  queue_to_multiverse assumes it's a valid pointer when it de-references it for packed_buffer_queue_add.

queue_to_multiverse should probably return if msi == NULL to prevent the segfault.

**Comment by smcameron** [comment]
Thanks.  Generally, I always run a multiverse server even if running only one snis_server (or I suppose I would have found this myself).

**Comment by smcameron** [comment]
This may fix it: 9b4af0051e87333956b84739e9042603271d89c7

Give it a try.

**Comment by CapnRobberts** [comment]
Yes that fixes the crash I was experiencing. Thank you.
