### ISSUE TITLE
Dead image on website

### ISSUE THREAD

**Issue by MCMic** [smcameron/space-nerds-in-space#249]
There is a typo in website source in the image URL in https://smcameron.github.io/space-nerds-in-space/#multiplayerinstructions , an extra comma at the end prevents the image from loading.

**Comment by smcameron** [comment]
Thanks.  Fixed by 9c2704086640e1a02501ba1fd4cfeb2fbf31fd7a :+1:  Fix bad img tag for multiplayer-setup.png
