### ISSUE TITLE
Doesn't compile on ArchLinux without some tweaking.

### ISSUE THREAD

**Issue by ghost** [smcameron/space-nerds-in-space#25]
I tried to compile the latest git on ArchLinux x86_64.
There's a few #include issues regarding "gtk/gtkgl.h" but my programming knowledge is insufficient to fix the problem and propose a patch.

**Comment by MCMic** [comment]
For some reason on Arch this is now setup like this:
```
ls -lh /usr/lib/pkgconfig/lua*
-rw-r--r-- 1 root root 669  3 oct.  04:09 /usr/lib/pkgconfig/lua51.pc
-rw-r--r-- 1 root root 442  3 oct.  04:11 /usr/lib/pkgconfig/lua52.pc
-rw-r--r-- 1 root root 425 10 juil.  2018 /usr/lib/pkgconfig/lua53.pc
-rw-r--r-- 1 root root 586  9 nov.  22:36 /usr/lib/pkgconfig/luajit.pc
lrwxrwxrwx 1 root root  27 10 juil.  2018 /usr/lib/pkgconfig/lua.pc -> /usr/lib/pkgconfig/lua
```

So you can use `pkg-config --libs lua52` (but not `lua5.2`)
This outputs `-llua5.2 -lm`, so I guess current Makefile is linking lua5.3 instead.

ldd confirms that, currently linking to lua5.3, not sure if it’s a big deal or not.

**Comment by MCMic** [comment]
What about something like:
```
LUALIBS=`pkg-config --libs lua5.2 --silence-errors || pkg-config --libs lua52 --silence-errors || pkg-config --libs lua || echo '-llua5.2'`
```
(silencing errors from the first 2 tries allow for having only one error output on screen when lua is not found)

**Comment by smcameron** [comment]
How does the following patch look?

commit bb34391d52e0a0ce3a6b30839b345bcd8240c5a3
Author: Stephen M. Cameron <stephenmcameron@gmail.com>
Date:   Tue Jan 15 08:48:49 2019 -0500

    Make pkgconfig detection of lua5.2 more robust, esp. for Arch linux

    Suggested-by: McMic <mcmic@free.fr>
    Signed-off-by: Stephen M. Cameron <stephenmcameron@gmail.com>

diff --git a/Makefile b/Makefile
index 120ccda..dddd041 100644
--- a/Makefile
+++ b/Makefile
@@ -403,8 +403,8 @@ ifeq (${OSX},0)
 # Arch pkg-config seems to be broken for lua5.2, so we have
 # this "... || echo" hack thing.
 #
-LUALIBS:=$(shell pkg-config --libs lua5.2 || echo '-llua')
-LUACFLAGS:=$(shell pkg-config --cflags lua5.2 || echo '')
+LUALIBS:=$(shell pkg-config --libs lua5.2 --silence-errors || pkg-config
--libs lua52 --silence-errors || pkg-config --libs lua --silence-errors ||
echo '-llua5.2')
+LUACFLAGS:=$(shell pkg-config --cflags lua5.2 --silence-errors ||
pkg-config --cflags lua52 --silence-errors || pkg-config --libs lua
--silence-errors || echo '')
 else
 # OSX needs to do it this way (what is the point of pkgconfig if they all
do it differently?)
 LUALIBS:=$(shell pkg-config --libs lua)

**Comment by smcameron** [comment]
Here's what the patch should have looked like:

```
Author: Stephen M. Cameron <stephenmcameron@gmail.com>
Date:   Tue Jan 15 08:48:49 2019 -0500

    Make pkgconfig detection of lua5.2 more robust, esp. for Arch linux
    
    Suggested-by: McMic <mcmic@free.fr>
    Signed-off-by: Stephen M. Cameron <stephenmcameron@gmail.com>

diff --git a/Makefile b/Makefile
index 120ccda..dddd041 100644
--- a/Makefile
+++ b/Makefile
@@ -403,8 +403,8 @@ ifeq (${OSX},0)
 # Arch pkg-config seems to be broken for lua5.2, so we have
 # this "... || echo" hack thing.
 #
-LUALIBS:=$(shell pkg-config --libs lua5.2 || echo '-llua')
-LUACFLAGS:=$(shell pkg-config --cflags lua5.2 || echo '')
+LUALIBS:=$(shell pkg-config --libs lua5.2 --silence-errors || pkg-config --libs lua52 --silence-errors || pkg-config --libs lua --silence-errors || echo '-llua5.2')
+LUACFLAGS:=$(shell pkg-config --cflags lua5.2 --silence-errors || pkg-config --cflags lua52 --silence-errors || pkg-config --libs lua --silence-errors || echo '')
 else
 # OSX needs to do it this way (what is the point of pkgconfig if they all do it differently?)
 LUALIBS:=$(shell pkg-config --libs lua)
```

**Comment by smcameron** [comment]
Committed bc326fcc8ed963509a18b47981e17d55bcf5f3a3

I'd be interested to see those warnings.  I'm guessing newer linux's than what I'm running have cranked up some options on gcc... probably nothing serious, but at the same time, some might be easy to fix anyway.

**Comment by smcameron** [comment]
The -Wno-gnu-folding-constant and -Wno-extended-offsetof options were added to allow the project to be built with clang in commit 3cf24a6

**Comment by MCMic** [comment]
I did not past the warnings before because I have them in french. I’m gonna figure out how to get everything in english and I will open a separate ticket with the complete output.

I guess it’s too late for this commit, but if you mention me in the future the case is supposed to be `MCMic` and not `McMic`. (Also the email was wrong but that was my fault the github account showed an obsolete one, fixed now)
