### ISSUE TITLE
Lua callback API weirdnesses

### ISSUE THREAD

**Issue by smcameron** [smcameron/space-nerds-in-space#250]
When snis_server starts, it runs the Lua script called "initialize.lua".  It never calls this script again.  Nothing useful is in this script.  It *might* be useful if it were called after clear_all(), so that things which persist might be put in there.  But probably we should just get rid of initialize.lua as there seems to be no need for it.

Timer callbacks are one-shot.  This is fine.  proximity callbacks are one-shots. This is fine.

Event callbacks do not appear to be one-shots.  Additionally multiple (3, MAXCALLBACKS in snis_event_callback.c) callbacks may be registered for one event. So far so good.  However, there appears to be no way to clear an event callback registration other than clear_all().  We should probably provide a way to clear an event callback registration, maybe something like:

```
unregister_callback(event_name, callback_function_name);
```

3 seems like a very low limit on number of callbacks per event, but the current implementation allocates space for all the possible callbacks per event, so that's why it's low.  Have not bumped into this limit (that I know of) so maybe it's fine, but seems like it could be made arbitrarily big without incurring any memory penalty with a little more work put into it by dynamically allocating the per-callback data as needed.

**Comment by MCMic** [comment]
Oh, so what royal-wedding does in end_mission does not work then, it tries to unregister callbacks by setting them to ""

**Comment by smcameron** [comment]
* c73f76eefa4652ea6ad031cf531b831230221c6e  Remove initialize.lua script and code that calls it 
* 45b290dc200ab9cf7506cffeb7f2e1f4efbfc626  Prevent registering the same event-callback tuple multiple times 
* dee412367b4a40f93d2c64fda75352812b890915  Allow Lua event callbacks to be unregistered

**Comment by smcameron** [comment]
> Oh, so what royal-wedding does in end_mission does not work then, it tries to unregister callbacks by setting them to ""

Fixed: 88919e6a9e3dd19eb52f9216fc180d1a6be938f2  Fix unregistering callbacks in royal wedding script

**Comment by MCMic** [comment]
Thanks

**Comment by smcameron** [comment]
Everything mentioned in this bug (except dynamically allocating event callbacks, which we do not have a demonstrated need for) has been addressed, so I'm closing this one.
