### ISSUE TITLE
Travel advisory and weird ETA bug

### ISSUE THREAD

**Issue by MCMic** [smcameron/space-nerds-in-space#266]
I found a TODO item in travel advisory section so I was starting to attempt to code this, so far I have this:
```
diff --git a/snis_server.c b/snis_server.c
index 00c9f29a..e6effaee 100644
--- a/snis_server.c
+++ b/snis_server.c
@@ -15961,7 +15961,6 @@ static void npc_menu_item_travel_advisory(struct npc_menu_item *item,
 {
        uint32_t plid, ch = botstate->channel;
        struct snis_entity *sb, *pl = NULL;
-       char *name;
        int i;
        uint16_t contraband = -1;

@@ -15979,26 +15978,22 @@ static void npc_menu_item_travel_advisory(struct npc_menu_item *item,
                i = lookup_by_id(plid);
                if (i >= 0) {
                        pl = &go[i];
-                       name = pl->sdata.name;
                        contraband = pl->tsd.planet.contraband;
-               } else {
-                       name = sb->sdata.name;
                }
-       } else {
-               name = sb->sdata.name;
        }

        if (pl) {
-               /* TODO: fill in all this crap */
-               send_comms_packet(sb, npcname, ch, " TRAVEL ADVISORY FOR %s", name);
+               struct planetary_atmosphere_profile *atm =
+                       planetary_atmosphere_by_index(pl->tsd.planet.atmosphere_type);
+               send_comms_packet(sb, npcname, ch, " TRAVEL ADVISORY FOR %s", pl->sdata.name);
                send_comms_packet(sb, npcname, ch, "-----------------------------------------------------");
                send_comms_packet(sb, npcname, ch, " WELCOME TO STARBASE %s, IN ORBIT", sb->sdata.name);
-               send_comms_packet(sb, npcname, ch, " AROUND THE BEAUTIFUL PLANET %s.", name);
+               send_comms_packet(sb, npcname, ch, " AROUND THE BEAUTIFUL PLANET %s.", pl->sdata.name);
                send_comms_packet(sb, npcname, ch, "");
-               send_comms_packet(sb, npcname, ch, " PLANETARY SURFACE TEMP: -15 - 103");
-               send_comms_packet(sb, npcname, ch, " PLANETARY SURFACE WIND SPEED: 0 - 203");
+               send_comms_packet(sb, npcname, ch, " PLANETARY SURFACE TEMP: %.0f K", atm->temperature);
+               send_comms_packet(sb, npcname, ch, " PLANETARY SURFACE PRESSURE: %.0f Pa", atm->pressure);
        } else {
-               send_comms_packet(sb, npcname, ch, " TRAVEL ADVISORY FOR STARBASE %s", name);
+               send_comms_packet(sb, npcname, ch, " TRAVEL ADVISORY FOR STARBASE %s", sb->sdata.name);
                send_comms_packet(sb, npcname, ch, "-----------------------------------------------------");
                send_comms_packet(sb, npcname, ch, " WELCOME TO STARBASE %s, IN DEEP SPACE", sb->sdata.name);
                send_comms_packet(sb, npcname, ch, "");
```

I put pressure instead of wind because wind is not known it seems. I put temperature in kelvin, not sure if something else is better?
I looked into changing «AROUND THE BEAUTIFUL PLANET» with something matching planet description but the planet description building code is complicated.

While testing this and keeping a planet in science details screen and orbiting it, I got this weird bug with ETA:
![Screenshot_20200305_144127](https://user-images.githubusercontent.com/106382/75989804-360bde00-5ef4-11ea-91bd-f0067d041042.png)
ETA was flickering between this and an empty value, sometimes in also showed 140min.

(This is not directly related to travel advisory but I already opened too much tickets for one day)

**Comment by smcameron** [comment]
Interesting about the ETA.  I guess it's because while in orbit you are purposely and always traveling almost exactly perpendicular to the direction that is toward the planet, so the ETA calculation gets weird.  The empty value is what it should be showing in that instance I suppose.  Looks like it's testing for a closing rate > 0.001.  That threshold seems too small.

As for the wind speed, etc. obviously what was there was just placeholder stuff, so whatever you can come up with is probably fine.

**Comment by MCMic** [comment]
It’s hard to find something that makes sense and is not a complete rewording of science details screen.
I’m thinking maybe nearest planet is an interesting information for travel advisory, as well as if there is a warpgate around.

> Interesting about the ETA. I guess it's because while in orbit you are purposely and always traveling almost exactly perpendicular to the direction that is toward the planet, so the ETA calculation gets weird. The empty value is what it should be showing in that instance I suppose. Looks like it's testing for a closing rate > 0.001. That threshold seems too small.

I get the same buggy behaviour when scanning the starbase I am docked to.

**Comment by MCMic** [comment]
@smcameron Is it ok if I alter nl_find_nearest_object_of_type to exclude the object we are giving him? I know the nearest planet to Ophep is Ophep, this is not the answer I expected xD

**Comment by smcameron** [comment]
> Is it ok if I alter nl_find_nearest_object_of_type to exclude the object we are giving him? I know the nearest planet to Ophep is Ophep, this is not the answer I expected xD

Ha.  Yeah, sure.

Fixed the ETA thing more or less: 1b4dca774814a749c7320f1342b1ef2d1933608f  Fix twitchy ETA values in science.

**Comment by MCMic** [comment]
@smcameron I thought my code was wrong, the starbase was telling we there is a warpgate while I could not find it.
It appears that the warpgate does not appear on science sensors even if I’m right in front of it and see it in nav and main screen. Is that on purpose? If warpgate are non-scannable, why is there an empty warpgate menu in science station?

**Comment by MCMic** [comment]
@smcameron Patch: 
[0001-Fix-travel-advisory-to-give-some-information.patch.txt](https://github.com/smcameron/space-nerds-in-space/files/4293737/0001-Fix-travel-advisory-to-give-some-information.patch.txt)

**Comment by smcameron** [comment]
> It appears that the warpgate does not appear on science sensors

Hmm, that does seem to be a bug.  However, you can get warp gates on science via comms, "/computer target the nearest warp gate".  You should also be able to select them on science normally, but it seems you can't.

I noticed your patch is looking up the nearest warp gate and planet.  Starbases can have an associated planet.  o->tsd.starbase.associated_planet_id will have the id of the planet the starbase is near, or -1 if it is in deep space.  So you don't need to use nl_find_nearest_object_of_type() for that.  There isn't a similar thing for the warp gates.

You should probably check the distance to the nearest warp gate.  It could be that the nearest one you find is very very far away, in which case you probably shouldn't mention it.

**Comment by MCMic** [comment]
I tried a lot with the computer but with warpgate instead of warp gate :-/

@smcameron I’m not showing the associated planet but the nearest planet to the associated planet, so that you know whereelse you could travel and what is around. (the associated planet is of course also stated as «IN ORBIT AROUND THE BEAUTIFUL PLANET %s», as before)

For warpgate, as they do not have an associated planet that I know of, I check the nearest warpgate and then checks that the nearest planet to that warpgate is ours, and if yes I consider it is orbiting our planet. Might not be the cleanest.

**Comment by smcameron** [comment]
> I tried a lot with the computer but with warpgate instead of warp gate :-/

Fixed by: 534086f4d5f173c8fc417b2d0996b83a83e69ccc  Make "warpgate" a synonym for "warp gate" 

The natural language stuff is no doubt tuned for the particular ways I formulate sentences.  When other people try to use it, they invariably do things a little differently and hit cases I don't manage to think of.

**Comment by smcameron** [comment]
> It appears that the warpgate does not appear on science sensors even if I’m right in front of it and see it ...

Fixed by: 4475821f5009c01e860788ae81390534e8794ea1  Transmit sdata for warp gates to clients

**Comment by smcameron** [comment]
> @smcameron Patch: 0001-Fix-travel-advisory-to-give-some-information.patch.txt

Committed as:
* 86c7017a2a73dd127259e4ae7cc15f330dca798c  Fix nl_find_nearest_object_of_type() to not report self 
* ead03f560faadb19ed8ad323b571141895df245d  Fix travel advisory to give some information.

**Comment by MCMic** [comment]
Thanks!
