### ISSUE TITLE
orientation from random looks incorrect.

### ISSUE THREAD

**Issue by CapnRobberts** [smcameron/space-nerds-in-space#270]
in snis_server.c there are a few places where a global object's orientation is setup using this code.
	go[i].orientation = random_spin[go[i].id % NRANDOM_ORIENTATIONS];

this is using a mixture of orientations and spins that does not look correct.

maybe it should be this?
	go[i].orientation = random_orientation[go[i].id % NRANDOM_ORIENTATIONS];

If it should be from random_spins that I think it should use NRANDOM_SPINS not NRANDOM_ORIENTATIONS, just in case they are ever set differently.

**Comment by smcameron** [comment]
Thanks.  Fixed by: 3fbb69b3ab21848c859dc8b628d0c2a103b56603  Fix incorrect use of NRANDOM_ORIENTATIONS

**Comment by CapnRobberts** [comment]
What are the differences between a "spin" and an "orientation"? Would this not init both the orientation and rotational velocity to the same quaterneon? It's the same index into the spins array.

	go[i].orientation = random_spin[go[i].id % NRANDOM_SPINS];
	go[i].tsd.asteroid.rotational_velocity = random_spin[go[i].id % NRANDOM_SPINS];

random_orientation is initialized by the server but never used, only random_spin is. It seems to be that the orientation should be setup with the random_orientation (static orientation) and spins would be for angular velocity (motion)

**Comment by smcameron** [comment]
The rotations in random_spin[] are small rotations (small angle, plus or minus 5 degrees max).  They are meant to be applied to an object repeatedly at 10Hz rate, for example, to spin asteroids or derelict ships around over time.

for random_orientation[] the angle may range from 0 to 360 degrees, randomly selected.  They are typically applied once when the object is created to set its initial orientation.

**Comment by CapnRobberts** [comment]
Then should not go[i].orientation use random_orientation not random_spin so it gets a valid initial orientation? Your commit still has the orientation being setup from a spin not an orientation, it just fixes the modulo.

**Comment by smcameron** [comment]
Er, looking at compute_arbitrary_spin(), actually I don't apply it continuously, I multiply the angle by a timestamp to compute how far something has rotated at any given moment.  It's been awhile since I looked at this.  I think there are some clever things to avoid sending the orientation for e.g. planets from server to client.

**Comment by smcameron** [comment]
Oh, yeah.  You're right.  Thanks!

**Comment by smcameron** [comment]
How's this look?

```
diff --git a/snis_server.c b/snis_server.c
index 5bd5428..d06d0d0 100644
--- a/snis_server.c
+++ b/snis_server.c
@@ -11536,7 +11536,7 @@ static int add_asteroid(double x, double y, double z, double vx, double vz, doub
        go[i].vz = snis_random_float() * ASTEROID_SPEED * 2.0 - ASTEROID_SPEED;
        go[i].tsd.asteroid.v = velocity;
        go[i].alive = snis_randn(10) + 5;
-       go[i].orientation = random_spin[go[i].id % NRANDOM_SPINS];
+       go[i].orientation = random_orientation[go[i].id % NRANDOM_ORIENTATION];
        go[i].tsd.asteroid.rotational_velocity = random_spin[go[i].id % NRANDOM_SPINS];
 
        /* FIXME: make these distributions better */
@@ -11578,7 +11578,7 @@ static int add_warp_core(double x, double y, double z,
        go[i].tsd.warp_core.countdown_timer = countdown_timer;
        go[i].tsd.warp_core.ship_id = ship_id;
        go[i].alive = 1;
-       go[i].orientation = random_spin[go[i].id % NRANDOM_SPINS];
+       go[i].orientation = random_orientatio[go[i].id % NRANDOM_ORIENTATIONS];
        go[i].tsd.warp_core.rotational_velocity = random_spin[go[i].id % NRANDOM_SPINS];
        return i;
 }
```

**Comment by smcameron** [comment]
Ok, this should do it: 8cba448a54191fcb16f4113b953c7c4c369bf079  Use random_spin[] not random_orientation[] to set initial object orie…

**Comment by CapnRobberts** [comment]
For your description of orientations, that makes the most sense to me.
