### ISSUE TITLE
add libpng-dev to required dependencies

### ISSUE THREAD

**Issue by eddriesen** [smcameron/space-nerds-in-space#283]
Installed on Xubuntu 18.04 and 20.04 and both wouldn,t compile due to missing libpng-dev 

Just adding the line to the build instructions would fix this issue.
Cheers!

**Comment by smcameron** [comment]
Thanks!

**Comment by smcameron** [comment]
Updated README.md and index.html on gh-pages branch

*  Add libpng-dev to dependencies 79deb5e6afbf2c2266cf5872f952a9d06fc48d7d
*  Add-libpng-dev-to-dependencies 917f7a055537f369e30eb96c48707b8e03f4c7c6
