### ISSUE TITLE
Error in add_mining_bot ?

### ISSUE THREAD

**Issue by MCMic** [smcameron/space-nerds-in-space#284]
Maybe I’m miss-reading this, but isn’t this code doing snprintf in o->sdata.name and right after use memset to set it to 0? And then use strncpy on same destination :thinking: 

```
	push_mining_bot_mode(o, parent_ship->id, asteroid_id, bridge, selected_waypoint);
	snprintf(o->sdata.name, sizeof(o->sdata.name), "%s-MINER-%02d",
		parent_ship->sdata.name, parent_ship->tsd.ship.mining_bots);
	memset(o->sdata.name, 0, sizeof(o->sdata.name));
	strncpy(o->sdata.name, parent_ship->tsd.ship.mining_bot_name, sizeof(o->sdata.name));
```

**Comment by smcameron** [comment]
Thanks.  You're not misreading it. Looks like I deleted one snprintf, but not the extra one, ha. 607b8f072635abd3bf1fd6ecc5da50652449ecb2  Slightly surprised that clang scan-build didn't call that out as a dead store, though I guess that might be asking a bit much of it.

* fix dead store in add_mining_bot() efdfa3c98127615a087b6d583f2c6a6d87e6ddc4

**Comment by MCMic** [comment]
Isn't the memset also redundant with strncpy?

**Comment by smcameron** [comment]
Hmm, yeah.  Fail at being paranoid.  I should probably go through and change all instances of strncpy to use strlcpy instead.

**Comment by smcameron** [comment]
For now: 522cf09f9fc3482780892d053b88f566cd7d0f4d

**Comment by smcameron** [comment]
Replaced all but one instance of strncpy with srlcpy (and can build without strlcpy if need be via a custom strlcpy implementation).

*  Replace strncpy with strlcpy (part 1 of 5)  5d8de8a2839f9d668599957836815f18acbadaaf
*  Replace strncpy with strlcpy (part 2 of 5) 90ad85f89f97ed85b54991240f1b7b12421bc35d
*  Replace strncpy with strlcpy (part 3 of 5) d95697a1ab85975b2e15b3be12918d8f3e97df35
*  Replace strncpy with strlcpy (part 4 of 5) 043661bb7b7678b7299fa9b7600152d83eb0ee52
*  Replace strncpy with strlcpy (part 5 of 5) 7de31e850c885759258ae94485e8d8b2055fb813

Did not attempt to do anything about use of strncat() yet.
