### ISSUE TITLE
Is GTK still a dependency?

### ISSUE THREAD

**Issue by MCMic** [smcameron/space-nerds-in-space#292]
I’m trying to fix my snis-live project following the migration to SDL2.
I removed GTK from dependencies but I see a lot of «Package 'gtk+-2.0', required by 'virtual:world', not found Package gtk+-2.0 was not found in the pkg-config search path. Perhaps you should add the directory containing `gtk+-2.0.pc' to the PKG_CONFIG_PATH environment variable» messages.

Is GTK still a dependency? 

It’s not listed in https://smcameron.github.io/space-nerds-in-space/#buildinstructions

**Comment by smcameron** [comment]
No, gtk should not be needed.  Hmm, there seem to be a few vestiges in the Makefile...

```
scameron@wombat ~/github/space-nerds-in-space $ grep gtk Makefile
GTKCFLAGS:=$(subst -I,-isystem ,$(shell $(PKG_CONFIG) --cflags gtk+-2.0))
GTKLDFLAGS:=$(shell $(PKG_CONFIG) --libs gtk+-2.0) $(shell $(PKG_CONFIG) --libs gthread-2.0)
scameron@wombat ~/github/space-nerds-in-space $ grep GTK Makefile
GTKCFLAGS:=$(subst -I,-isystem ,$(shell $(PKG_CONFIG) --cflags gtk+-2.0))
GTKLDFLAGS:=$(shell $(PKG_CONFIG) --libs gtk+-2.0) $(shell $(PKG_CONFIG) --libs gthread-2.0)
LIMCOMPILE=$(ECHO) '  COMPILE' $< && $(CC) -DWITHOUTOPENGL=1 ${MYCFLAGS} ${GTKCFLAGS} -c -o $@ $<
ELLINK=$(ECHO) '  LINK' $@ && $(CC) ${MYCFLAGS} -o $@ ${GTKCFLAGS} ${OD}/earthlike.o ${ELOBJS} ${ELLIBS} $(LDFLAGS)
MCLINK=$(ECHO) '  LINK' $@ && $(CC) ${MYCFLAGS} -o $@ ${GTKCFLAGS} util/mask_clouds.o ${MCOBJS} ${MCLIBS} $(LDFLAGS)
CMNMLINK=$(ECHO) '  LINK' $@ && $(CC) ${MYCFLAGS} -o $@ ${GTKCFLAGS} util/cloud-mask-normalmap.o ${CMNMOBJS} ${CMNMLIBS} $(LDFLAGS)
	$(CC) -DTEST_NAMES -o bin/names ${MYCFLAGS} ${GTKCFLAGS} ${OD}/mtwist.o names.c
	$(CC) -DTEST_STL_PARSER ${MYCFLAGS} ${GTKCFLAGS} -o bin/stl_parser stl_parser.c ${OD}/matrix.o ${OD}/mesh.o ${OD}/mathutils.o \
	$(CC) ${MYCFLAGS} ${GTKCFLAGS} -DTEST_MATRIX -o bin/test-matrix matrix.c -lm
```

I don't think it's actually needed though.  The limited client doesn't exist anymore (because it needed gtk).

Makefile needs cleaning up, I guess. (If you grep for gtk in *.c, you'll see some stuff, but I think they are all ifdef'ed out.)  But it's been a little while and I didn't look super hard, so I might have missed something.  Will look a bit later, currently watching the last 30 minutes of Trump's time finally expire.

**Comment by smcameron** [comment]
Ok, try this:

95d6ca68f7d108e37a3c42f1e2f9d9eb5b3041c4 Remove most remaining vestiges of gtk  

at top of master.

**Comment by smcameron** [comment]
Pretty sure this is fixed, so I'm going to close it.  I don't have any machines that don't have gtk-dev stuff installed to really test it out though.  Feel free to re-open this if you find that I missed something.

**Comment by MCMic** [comment]
Sorry for not answering earlier, from what I’ve seen this is fixed indeed.

There is an uptodate ISO on https://snis.mugoreve.fr/ but I did not test it yet.

**Comment by smcameron** [comment]
Updated the "hacking" doc re the GTK to SDL2 transition:

*  Update hacking doc after GTK to SDL transition  c74103a20b45dfb96225c8cf932b04dfcec234c3
