### ISSUE TITLE
Build failure linking snis_client.o

### ISSUE THREAD

**Issue by CategoryQ** [smcameron/space-nerds-in-space#293]
I updated the source today (2021-02-03), but running make failed linking snis_client.o

Error message below, running on Debian 10 Buster with all dependencies successfully installed:-

`/usr/bin/ld: object_files/snis_client.o: in function `connect_to_lobby_thread':
snis_client.c:(.text+0x9e0): undefined reference to `ssgl_gameclient_connect_to_lobby_port'
/usr/bin/ld: object_files/snis_client.o: in function `synchronous_update_lobby_info':
snis_client.c:(.text+0xd64): undefined reference to `ssgl_gameclient_connect_to_lobby_port'
collect2: error: ld returned 1 exit status
make: *** [Makefile:959: bin/snis_client] Error 1`

**Comment by smcameron** [comment]
Can you try:

```
make mostly-clean
make
```

And see if that fixes it? ... just to rule out that it might be the Makefile doesn't express all the dependencies perfectly and it's trying to link some old objects or something.

(FWIW, a fresh clone and build works fine for me, not that that is much help for you.)

**Comment by CategoryQ** [comment]
Perfect, that has resolved it thanks.

Initially make clean didn't help, but looking back at my terminal I think I had a typo - "make clran" failed!
