### ISSUE TITLE
Widget positions

### ISSUE THREAD

**Issue by MCMic** [smcameron/space-nerds-in-space#294]
Hello,

The warpdrive control was hidden after launching the game, I had to use the demon screen to reset widget positions to get it back. This was the first time I launched the build with widget position configuration so I expected it at its default place.

Is there a key binding to reset widget ui position? I usually disable demon screen on stations.

**Comment by MCMic** [comment]
I had a similar problem with mainmenu, the buttons were hidden the first time, all over the place the second time, I had to use reset ui widgets from demon screen to fix it.

**Comment by smcameron** [comment]
Yikes.  Thanks for reporting that.  I'll look into it.

**Comment by smcameron** [comment]
This is not currently any keybinding to reset the widget positions.

**Comment by smcameron** [comment]
What does the file ~/.local/share/space-nerds-in-space/snis_ui_position_offsets.txt look like?

**Comment by smcameron** [comment]
Ok, I made a couple of commits that might help, let me know whether this fixes the problem for you:

* 3df8e0042ba91e22e82703c46eafc93aec8d6b93  Annotate snis-ui-widget-offsets.txt file with widget names 
* 221efd491a08e658abf48ca1740791ed911257f8  Set xy offsets to zero in ui_element_init()

**Comment by MCMic** [comment]
This file does not exists:
```
$ ls ~/.local/share/space-nerds-in-space/
default_ship_name.txt  role_defaults.txt
```

**Comment by MCMic** [comment]
The commits do fix the problem, at least of the main menu.
