### ISSUE TITLE
Station asking to lower shield which are already low

### ISSUE THREAD

**Issue by MCMic** [smcameron/space-nerds-in-space#297]
It seems to please the station and get permission to dock you have to cut the power from the shield (using the slider on the left), lowering shields using the slider on the right did not work, the station kept telling me I need to lower my shields.

This makes the slider on the right a bit useless.

**Comment by smcameron** [comment]
Thanks.  This should fix it:

0118217a594bc00507c2a04f48c7fcb5c527df3e  Starbases should not care by which method you lower shields
