### ISSUE TITLE
Installation guide isn't listing libsdl2-image-dev

### ISSUE THREAD

**Issue by DonFruendo** [smcameron/space-nerds-in-space#314]
OS: Pop!_OS 20.04 (Ubuntu 20.04 derivative)

I followed the update guide [here](http://smcameron.github.io/space-nerds-in-space/#buildinstructions), but was unable to `make` until i installed `apt install libsdl2-image-dev`. The failing bit was this code:
```bash
  COMPILE snis_client.c
snis_client.c:54:10: fatal error: SDL2/SDL_image.h: No such file or directory
   54 | #include <SDL2/SDL_image.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:888: object_files/snis_client.o] Error 1
```
I did install `libsdl2-dev` and `libsdl2-2.0-0` beforehand as described in the guide, but that was apparently not enough :disappointed: 

Maybe you could add a hint to the file that this package can be required :slightly_smiling_face: 
Thanks!

**Comment by smcameron** [comment]
Thanks for pointing it out, I think it's a recent commit that introduced this dependency: 9baabd1d4f533a8b0dd9f7a49fc71bf097090f15

**Comment by smcameron** [comment]
Should be fixed by these two commits that update the README.md and gh-pages index.html files.

* d1f19edcbe6d31735ae48dba5477851a1de47c0e
* 6554640d048130cab48c88668f3f361028f372ce
