### ISSUE TITLE
scan contact velocity is a single number, should be three

### ISSUE THREAD

**Issue by heaventwig** [smcameron/space-nerds-in-space#341]
On the science screen, when viewing details about a scanner contact, velocity is represented as a single number.

Once I thought about this for a while, I realized I would expect this to be a triplet representing the _contact's_ bearing, mark, and ±speed. (In addition to the bearing, mark, range, and so on from my ship to the contact.)

**Comment by smcameron** [comment]
Hmm.  Maybe.  There's limited screen space though, and differentiating the direction from the player ship to the object vs. the direction of the object's motion seems difficult to do in a way that's not confusing, and finally, what are you going to *do* with this information?  If there's something useful that can be done with this information, then there's a stronger case for putting it on screen.

If you're thinking about setting an intercept course... the way I usually do that is get the object on the main view, than change my speed/direction until the object remains stationary on the main view... and that's an intercept course, provided you have enough speed to catch up to it, and you can get an ETA and closing rate on science as it stands.

**Comment by heaventwig** [comment]
Yeah, this whole "what will you do with it" line of inquiry is a good one. I thought about intercept courses, and thought about instead displaying intercept courses at current impulse power, and immediately thought of doing it for warp, and realized no, that's silly, warp just gets you there. And that's when I stopped thinking intercept courses made sense.

I think this does reduce this issue submission to a semantic quibble over the difference between velocity and speed, and a desire to change the science display to say "speed" because it's more accurate... but velocity is more fun, and I think that's more important than accuracy.

**Comment by smcameron** [comment]
I think speed is more useful (and therefore more fun) than velocity, because you can tell if, e.g. a floating cargo container is moving away from you faster than your ship can travel on impulse drive.  "Velocity" also seems like a more ["space-word" thing to say](https://www.youtube.com/watch?v=ipbGsHL1oZw) than "speed", so subtly influencing the science officer to say, "Captain, the object is moving away at a velocity of such and such" instead of "a speed of such and such", seems like it might be better, even if it is a technically incorrect colloquialism.

**Comment by heaventwig** [comment]
Oh, is it actually currently displaying the component of the scanner contact's velocity relative to the line connecting it to the player ship? Because *that* seems useful and actionable. And "relative velocity" gives us more space-words, and more information about what's happening on screen. (This suggests a separate question about F1 help texts, and whether they can easily be made context-specific for screens that, like science (also nav's starmap, maybe others) have multiple displays.)

**Comment by smcameron** [comment]
There is "closing rate", which iirc, is the relative velocity projected onto a vector from the ship to the object, or it might be sampled numerically (difference of two distance samples / time between samples) which amounts to the same thing.  Positive values mean moving towards each other, negative means away, and ETA is iirc, just distance / closing rate.

**Comment by smcameron** [comment]
Closing this because I don't think it's useful enough to warrant the screen space.
