### ISSUE TITLE
missile launch failure

### ISSUE THREAD

**Issue by heaventwig** [smcameron/space-nerds-in-space#344]
On the weapons screen, the N key triggers sounds but no other activity, including no decrement of the missile count. If there's a missile lock process required first, it's not reflected in the help screen documentation.

**Comment by smcameron** [comment]
f5ae309413a562f19ed350bffcc83e5db4a0e9eb Provide hints to trigger happy weapons officers

**Comment by smcameron** [comment]
Oops...

2c6fdc3597b1e10d5f6fbadd9f85bf8fa9528aa7 Add missing return to process_adjust_control_fire_missile()

**Comment by smcameron** [comment]
60597063da46f546a40f0ea88c4e555e9f67a81a Mention in-range targeting requirement in weapons help text

**Comment by heaventwig** [comment]
That's fantastic. Thank you!
The updated help text does suggest a question though -- what's the range on the missile lock?
