### ISSUE TITLE
weapons screen controls request: phaser wavelength hotkeys

### ISSUE THREAD

**Issue by heaventwig** [smcameron/space-nerds-in-space#348]
I'd love to be able to set phaser wavelength to within 5 NM with the push of a single hotkey. Could be numbers 1-9, 0, and the minus key. Then = and ] could be fine tuning adjustments up and down.

**Comment by smcameron** [comment]
* d7f2496ad5bf4492764fd58958c7040010d248d8 Allow weapons wavelength to be selected via number keys

You can now use 0 - 9 to set the phaser wavelength, and '-' and '=' to adjust up and down.
