### ISSUE TITLE
helm controls requests

### ISSUE THREAD

**Issue by heaventwig** [smcameron/space-nerds-in-space#349]
keybindings for these:

1. adjust zoom ±
2. adjust throttle ±
3. adjust warp drive ±
4. toggle reverse impulse drive
5. engage warp
6. engage docking magnets
7. standard orbit
8. starmap (toggle)
9. toggle lights

**Comment by smcameron** [comment]
Zoom is already there, default is = or + to zoom in, and - to zoom out.  the actions are "zoom" and "unzoom".

**Comment by heaventwig** [comment]
I believe I tested those, so ... I should test them again and if I can duplicate the error I should file a bug report.

**Comment by smcameron** [comment]
* c1feb09bb0905577347e00ca9e5f977d9badc83f Fix bug in remapkey()
* a913cb9693587470b997c25f83fd2bf098ebebda Update man page about keymap.txt
* 7b33c9121567c577f7e264af1aae3ab163e70277 Add slash to keyname_value_map[]
* ea2c96ead93dd5e70ca314a2e004785102045900 Allow printing keymaps
* 79953fba287e5e09c70ada0ce14c67035ad4d2ad Allow warp drive to be adjusted up/down via < and > keys on Nav
* 09cea3572d58cd69e05d044510877f001a56cfa9 Allow impulse drive to be adjusted up/down via keys on nav
* 5c5208d574f18fe127a8dfa3be8f21b5ca9a5392 Allow engage warp via keyboard on nav screen
* cca19d1f0ec943aef616fb2f0e959e8236946e54 Allow reverse impulse via nav keyboard
* 4dc0d6ac90adaf7543680e374b2178c72fb53969 Allow engage docking magnets via Nav keyboard
* bfe757e54ec4863d95d3ef9bcff172dce7aea087 Allow exterior lights via nav keyboard
* 063735c98ed7e08c3f24415d37b6d99fef407f32 Allow standard orbit via Nav keyboard
* aa27047044b99d91534936e19c4558a4520810cd Remove unused keytransform key
* 3a98e44f15da9cfb5cc787f49c4a2526e979a902 Allow toggling starmap via nav keyboard

New default keys are:

t = starmap
b = standard orbit
i = exterior lights
x = docking magnets
backspace = reverse
slash = engage warp
right square bracket = increase impulse
left square bracket = decrease impulse
comma ( < ) = decrease warp drive
period ( > ) = increase warp drive

Still need to document those in the help.

**Comment by heaventwig** [comment]
Awesome — thank you! That helps me a bunch. And if you point to the spot where the help files live, I can probably submit a patch with the updated help text. Start me editing the code-base and contributing more than suggestions and requests!

**Comment by smcameron** [comment]
If you are really interested in working on the code, you should look at this, if you didn't already find it: https://htmlpreview.github.io/?https://github.com/smcameron/space-nerds-in-space/blob/master/doc/hacking-space-nerds-in-space.html

**Comment by smcameron** [comment]
Thanks for the pull request:

* 4207c234b89132b275814a6736c3822595151630 Update nav screen help text with default key bindings

**Comment by smcameron** [comment]
I think that's everything, so I'm closing this.  Feel free to re-open if I missed something.
