### ISSUE TITLE
Compile issue - mathutils.c

### ISSUE THREAD

**Issue by drofsirreb** [smcameron/space-nerds-in-space#355]
First time I'm trying to install this.
Using an old laptop with Ubuntu 18.04.6

All went well until the point where I run the 'make' command.. I then get the following:

COMPILE mathutils.c
cc: error: unrecognized command line option '-Wstringop-truncation'; did you mean '-Wline-truncation'?
Makefile:967: recipe for target 'object_files/mathutils.o' failed
make: *** [object_files/mathutils.o] Error 1

Any advice would be appreciated

**Comment by smcameron** [comment]
Glad you figured it out.

Yeah, stringop-trunction was added in gcc 8, in 2018.  Another option would have been to delete -Wstringop-truncation from COMPSPECCFLAGS in the Makefile.
