### ISSUE TITLE
Android tablets and Wasm?

### ISSUE THREAD

**Issue by GonzalezAtWork** [smcameron/space-nerds-in-space#361]
Hey guys,

Just got to know this project and I think it is awesome!

But that make me visualize an "house structure" for a bridge, like:
55" android/samsung television as main screen
5 android tablets for each station

maybe using wasm and running from the browser?

**Comment by smcameron** [comment]
The tablet idea is a non-starter.  Too many keyboard things required, including typing in the Comms station.

As for WASM, also not happening.  Looked into it a bit, see #277  There are too many linux-isms and unix-isms and converting the network code from sockets to websockets is non-trivial, and all that for a shitty in-browser experience at the end of the day.
