### ISSUE TITLE
minor bug in gaseous-giganticus.c 

### ISSUE THREAD

**Issue by JohnVV** [smcameron/space-nerds-in-space#52]
Minor bug with using a cubemap ( NO "-s" or "-S" ) in gaseous-giganticus.c 

at the end will be a link to a zip file with examples 

a cube map is normally h =3 w=4  proportion 

reading in the width is FINE  however the tile height that is not correct 

the tile height is being inputed as 3/4 of the 1024 rows then outputing a 1024 image ( of the 768 rows read) 

so far i have NOT been able to find the loop that is causing this read error 

included in the zip is a standard test image i use simple cylindrical 10 degree lines 
a cube map of it 
and a "work around " remapped cube map that DOSE work 
but that is a work around only 

for a correct cube map --- not outputting correctly 
./gaseous-giganticus -c 1  --noise-scale 0.1 --velocity-factor 1 -i ./lines10Cube.png --bands 1

a "fudged cubemap that will output correctly "lines10Cube1.png"
./gaseous-giganticus -c 1  --noise-scale 0.1 --velocity-factor 1 -i ./lines10Cube1.png --bands 1

" Test.zip"
https://drive.google.com/file/d/0B6ZYAd08tZL-UnREOGtRMy04UGM/view?usp=sharing

**Comment by smcameron** [comment]
Thanks.

Yeah, the 'P' or --plainmap thing is a bit of a hack -- I made sinusoidal the default, and that is what I generally use.

I think it is probably reading in the image correctly, I expect the mistake is in init_particles(), which randomly places particles on the surface of a sphere and initially sets their colors according to some method of mapping from the sphere back to the image.  I expect it is this mapping which is incorrect... in this code, which I recall was a pain in the ass, and evidently still isn't right.

                    if (!stripe && !sinusoidal) {
                        fij = xyz_to_fij(&p[i].pos, DIM);
                        if (fij.i < 0 || fij.i > DIM || fij.j < 0 || fij.j > DIM) {
                                printf("BAD fij: %d,%d\n", fij.i, fij.j);
                        }
                        xo = XDIM * face_to_xdim_multiplier[fij.f] + fij.i / 4.0;
                        yo = YDIM * face_to_ydim_multiplier[fij.f] + fij.j / 4.0;
                        xo = xo / (float) XDIM;
                        yo = yo / (float) YDIM;
                        px = ((int) (xo * start_image_width)) * 3;
                        py = (((int) (yo * start_image_height)) * start_image_bytes_per_row);
                        //printf("x,y = %d, %d, pn = %d\n", px, py, pn);
                } else if (stripe) {

**Comment by smcameron** [comment]
Ok, I see the problem, I think.  This commit should fix it, I think: 6a86ed99959dd228891580c201cbe26c56514e0d

Let me know if this fixes it for you.

**Comment by smcameron** [comment]
BTW, thanks for the test images.  It brought to my attention some wicked spinning at the poles, which makes me think I should attenuate the band velocity * sin(lattitude) or something.

**Comment by smcameron** [comment]
Alright, I am going to close this issue because I am pretty certain it's fixed.  Feel free to re-open it if you're still having trouble with this.
