### ISSUE TITLE
When planets are deleted the atmosphere remains behind

### ISSUE THREAD

**Issue by smcameron** [smcameron/space-nerds-in-space#56]
When planets are deleted (via the demon screen, either by selecting and deleting or via running the "clear all" command, or via lua script) their atmospheres remain behind.

**Comment by jv4779** [comment]
The atmosphere entity isn't a child of the planet like the rings?

**Comment by smcameron** [comment]
No, that was the first thing I tried.  Oddly, making the atmosphere entities children of the planet entities like the rings makes the atmospheres not render at all.  Have not yet looked into why that is.

**Comment by smcameron** [comment]
I think it may be because the child is inheriting in some way the scale from the parent? In entity.c, in update_entity_child_state...

union vec3 scale = e->e_scale;
...
while loop to walk the child/parent chain, only 1 level deep in this case...
   ...
   vec3_cwise_product_self(&scale, &parent->e_scale);
...
e->scale = scale;

Curently I am setting the planet scale to planet->r * 1.03;  so maybe the above code is setting it to (r * r * 1.03) which is quite huge, making it fail to render?  Tried setting scale of atmosphere to just 1.03 hoping to have the above parent-child chain walking code do the multiply but did not seem to work.  I am a little confused about the above code, as it looks like it will accumulate successive multiplies in e->scale, which does not seem like the right thing to do (but somehow the planet rings work, so I must be missing something.)

**Comment by smcameron** [comment]
Ok, I figured out part of the problem... was storing away things in go[-1], which doesn't work so well.  Still having some problems with the parent/child entity system though, so for now I am not using it in this particular case.  Need to revisit that though.  For now, see commit: 780468f35ab4ab319d5d8b36d9da4dff9f8fbc6d

**Comment by smcameron** [comment]
Ok, fixed this properly with commit d8dd1f5ab87579ca0407793f1e6b579ff17b4e03
