### ISSUE TITLE
Compiling fails No rule to make target share/snis/models/docking_port2.stl

### ISSUE THREAD

**Issue by at-boy** [smcameron/space-nerds-in-space#57]
OPENSCAD share/snis/models/docking_port.scad
make: *** No rule to make target `share/snis/models/docking_port2.stl', needed by `all'.  Stop.

**Comment by psymin** [comment]
Do any other scad files build?  Which version of openscad do you have?

**Comment by at-boy** [comment]
Yes there are other scad files that looks like they are building without a problem

OpenSCAD version 2014.01.29

**Comment by smcameron** [comment]
Quite possibly I broke it recently as I have been mucking about in this
area lately and may have missed git adding a file.  Will take a look
tonight after work if I can find time.

**Comment by smcameron** [comment]
Ok, commits e3466381488663c9bb4f0ee5e1b55397950317d1 and 5d6a94f51a725ee3d3b5d33002e1e8c2e7bd4ad7 should make it build.  Let me know if they don't.  Sorry about that.

**Comment by at-boy** [comment]
Thanks it compiles excellently and the seems to work
