### ISSUE TITLE
"S" key doesn't work in several screens

### ISSUE THREAD

**Issue by hef** [smcameron/space-nerds-in-space#61]
"S" key doesn't work in NAV, Sensors, or Science screens.

It works as a text entry key in coms

**Comment by smcameron** [comment]
Thanks for reporting this.  I think commit 359f1b4955496b9b62a1e1510f01f89d787a8611 fixes this.  It got broken when I added the space dust toggle key on 'ctrl-s', but it ate the 's'.  So I moved the space dust toggle to 'f' now -- 'f' for 'fake stars'.  Let me know whether this fixes it for you.

**Comment by smcameron** [comment]
Closing this since I think it's fixed.
