### ISSUE TITLE
Allow player ships to travel between instances of snis_server

### ISSUE THREAD

**Issue by smcameron** [smcameron/space-nerds-in-space#65]
Allow player ships to travel between instances of snis_server.  Quite likely this is a bad idea.  But it is fun to think about.

The idea would be that each snis_server hosts a single star system (as it does now) but by, for example, paying a toll at a jumpstation and selecting a destination system (possibly a limited choice from among a larger set of possibilities based on some graph that links the systems together) the players (all snis_clients associated with a particular ship) could disconnect from the current snis_server and reconnect to a different snis_server and effectively travel to another system.

Some things to think about:
- All the attributes of the ship (fuel, damage, etc) should travel with the ship.
- Security (by far the toughest part of this).
- Probably need some "meta server(s)" to track player ship information independent of snis_server instances, and to track and contain the graph of connections between snis_server instances.
- Snis server instances would need to talk to this meta server(s) to get player info and to become aware of their position in the graph and the other snis_servers they might reach.

**Comment by smcameron** [comment]
Ton of commits today that go a significant way towards making this a reality.

```
git diff 8d8dd83 e8e9842 | diffstat
 Makefile                                    |   44
 README                                      |    3
 graph_dev.h                                 |   15
 graph_dev_gdk.c                             |   33
 graph_dev_opengl.c                          |  182 +++
 key_value_parser.c                          |  458 +++++++++
 key_value_parser.h                          |  103 ++
 quat.c                                      |   10
 quat.h                                      |    4
 quickstart                                  |   59 +
 share/snis/models/warpgate.scad             |   38
 share/snis/solarsystems/default/assets.txt  |    3
 share/snis/solarsystems/default2/assets.txt |   14
 snis.h                                      |   20
 snis_bridge_update_packet.c                 |  200 ++++
 snis_bridge_update_packet.h                 |   35
 snis_client.6                               |    2
 snis_client.c                               |  766 +++++++++++++---
 snis_hash.c                                 |  106 ++
 snis_hash.h                                 |   32
 snis_marshal.h                              |    5
 snis_multiverse.6                           |   37
 snis_multiverse.c                           | 1336 ++++++++++++++++++++++++++++
 snis_multiverse.h                           |   19
 snis_packet.h                               |   12
 snis_server.6                               |   47
 snis_server.c                               | 1199 ++++++++++++++++++++++++-
 snis_server_tracker.c                       |  243 +++++
 snis_server_tracker.h                       |   18
 solarsystem_config.c                        |   54 -
 solarsystem_config.h                        |    2
 ssgl/ssgl.h                                 |    1
 ui_colors.h                                 |    2
 33 files changed, 4877 insertions(+), 225 deletions(-)

```

**Comment by HUg0005** [comment]
Hasn't this been implemented?

**Comment by smcameron** [comment]
Mostly. I don't really consider it quite complete though.

**Comment by smcameron** [comment]
Improved robustness of warp gate traversal with the following commit:

* cbcbfe7fd4efd5725979c4458623b264465ef1f2

Also, improvements in how the client handles being disconnected from the server help when things go wrong:

* a68861749d9278b4035e2d5b1be386cd43c7c8c6
* 213414e9e925bf342bf2a6e55d22fcbc19cc3c58
* a69318b5a820038570e3a5d8b7e6b75146da97f2

The code for the warp gates is still a bit of a hacky mess though, so I won't close this yet.

**Comment by smcameron** [comment]
With the implementation of "auto wrangling" in multiverse, I guess this is more or less complete.  Still hacky, but I don't have specific ideas about how I want to improve it.
