### ISSUE TITLE
lock mouse on weapons role

### ISSUE THREAD

**Issue by wec22** [smcameron/space-nerds-in-space#69]
mouse should lock when on the weapons screen, so when moving with the mouse you can go around 360 degrees.  currently locked to 180.

**Comment by smcameron** [comment]
Hi.  I am not sure what you mean by "lock" the mouse.  Right now the way it works is, when the X position of the mouse is centered (half way from left and right sides of window) then the guns point straight ahead, and when the mouse is at the left or right edge of the screen the guns point backwards.  When the Y position of the mouse is at the top of the screen, the guns point straight up, and when the Y position of the mouse is at the bottom of the screen, the guns are lowered to be parallel with the body of the ship.

This means if you want to point the guns straight ahead, you move the mouse X position of the mouse to be in the center of the screen, etc.  You can judge the position of the guns relative to the ship by the position of the mouse on the screen.  It may take some getting used to.

I am not sure what control scheme you are suggesting.  I don't know what "mouse should lock" means.

**Comment by loansindi** [comment]
I think he's referring to the sort of mouse control you have in an FPS - the cursor goes away and there's no bounds to movement (so if I move my mouse to the right, my view always goes to the right).

**Comment by kwadroke** [comment]
Web browsers can also do this for games, if you give it permission to do so.

**Comment by wec22** [comment]
sorry for the confusion. my intent was like what @loansindi was saying.  when using the keys the view goes farther than the mouse does which is annoying.

**Comment by smcameron** [comment]
I'm going to need a more precise description of the desired behavior than the above vague half-assed descriptions so far on offer.  Preferably, send a patch implementing the behavior you want, but make sure the current behavior is also still an option, as what little I can get out of the above descriptions actually sounds kind of annoying.  Patch or it's not happening.
