### ISSUE TITLE
Cannot build for Debian 8 / SteamOS

### ISSUE THREAD

**Issue by ProfessorKaos64** [smcameron/space-nerds-in-space#72]
It seems there is a manpage missing. The mange page source dir, being set to the current directory of build, only contains earthlike.1, not .6. Maybe adding a second block to install to /share/man/man1 for the .1 shell commands is what is needed? Just some thoughts.

[Makefile](https://github.com/smcameron/space-nerds-in-space/blob/7fa133c9b1f04d2ef50aa6ac662731732e22e565/Makefile) snippet
```
${MODELSRCDIR}/starbase6.docking_ports.h \
	${MODELSRCDIR}/starbase.docking_ports.h

MANSRCDIR=.
MANPAGES=${MANSRCDIR}/snis_client.6.gz ${MANSRCDIR}/snis_server.6.gz \
	${MANSRCDIR}/earthlike.1.gz ${MANSRCDIR}/gaseous-giganticus.1
MANDIR=${DESTDIR}/${PREFIX}/share/man/man6
```

Building gives the following:
```
  LINK util/mask_clouds
gzip -9 - < snis_client.6 > snis_client.6.gz
gzip -9 - < snis_server.6 > snis_server.6.gz
gzip -9 - < earthlike.6 > earthlike.6.gz
/bin/sh: 1: cannot open earthlike.6: No such file
Makefile:795: recipe for target 'earthlike.1.gz' failed
make[2]: *** [earthlike.1.gz] Error 2
make[2]: Leaving directory '/home/desktop/build-snis-temp/snis'
debian/rules:36: recipe for target 'override_dh_auto_install' failed
make[1]: *** [override_dh_auto_install] Error 2
make[1]: Leaving directory '/home/desktop/build-snis-temp/snis'
debian/rules:22: recipe for target 'binary' failed

```

**Comment by smcameron** [comment]
Thanks for pointing this out.  I think commit 8abe94497135bb5eab3bd88af464919667f8f140 should fix the man page issue.  Let me know how it goes.

**Comment by ProfessorKaos64** [comment]
haha I just* did that and was going to submit a PR :) I'll try this in a new build now. Thanks @smcameron !

**Comment by ProfessorKaos64** [comment]
New missing file, bin/util/mask_clouds
```
gzip -9 - < snis_client.6 > snis_client.6.gz
gzip -9 - < snis_server.6 > snis_server.6.gz
gzip -9 - < earthlike.1 > earthlike.1.gz
mkdir -p /home/desktop/build-snis-temp/snis/debian/snis//usr/bin
install -m 755 ssgl/ssgl_server /home/desktop/build-snis-temp/snis/debian/snis//usr/bin
for x in snis_server snis_client snis_limited_client mesh_viewer util/mask_clouds ; do \
	install -m 755 bin/$x \
			/home/desktop/build-snis-temp/snis/debian/snis//usr/bin; \
done
install: cannot stat ‘bin/util/mask_clouds’: No such file or directory
```

**Comment by smcameron** [comment]
Ok, try now.  Commit b9298c5f6b28f3586f15d5742e1bc82526572615 and commit
69e825cb1965d68795750f74e62329e39237c3c2  (needed 2 tries to get it right -- at least I hope it's right.)

Obviously I don't test all these makefile paths well enough. :-/

-- steve

**Comment by ProfessorKaos64** [comment]
Testing again now. No, don't worry, I think it's enjoyable to work through the issues like this. I have some folks I am building this for on SteamOS, they'll enjoy it. Don't sweat it.

**Comment by ProfessorKaos64** [comment]
Build completes. Testing basic startup/functionality.

**Comment by ProfessorKaos64** [comment]
Launches in desktop mode and SteamOS :) Thank you for your help. I see the icon you use for the desktop file is pretty basic. Would you be open to a fanart submission if I make something up? maybe just a mashup of some stuff from screenshots you already have posted.

**Comment by smcameron** [comment]
>  I see the icon you use for the desktop file is pretty basic. Would you be open to a fanart submission if I make something up? 

There's an icon?  I don't think I made it... maybe it's some default.  If you want to try to make something, sure, go ahead.  I am not sure what to do with an icon image to make it actually do anything though.

**Comment by ProfessorKaos64** [comment]
Well, once I make something, you just need to install the file to a location you want (I am lazy and install to $HOME/Pictures in my scripts). Then you just need to change the target in the [dekstop file](https://github.com/smcameron/space-nerds-in-space/blob/de515c6bc8db62f8b34e473d48c243714508e3f1/snis.desktop).

**Comment by smcameron** [comment]
Ah, I had completely forgotten that @her001 had sent me that.

-- steve

**Comment by ProfessorKaos64** [comment]
I'll make something up and just link it here when I'm done. Even if something basic, better than the system monitor :) Great work, keep it up!

**Comment by smcameron** [comment]
Hmm, I wonder what the copyright status on the NASA "worm" logo or
"meatball" logo is?  a SNIS version of those might be cool...

**Comment by smcameron** [comment]
According to the wikipedia page:

"Like most images produced by the United States Government, the insignia,
the "worm" logo and the NASA seal are in the public domain
<https://en.wikipedia.org/wiki/Public_domain>.[*citation needed
<https://en.wikipedia.org/wiki/Wikipedia:Citation_needed>*] However, their
usage is restricted under Code of Federal Regulations
<https://en.wikipedia.org/wiki/Code_of_Federal_Regulations> 14 CFR 1221.[9]
<https://en.wikipedia.org/wiki/NASA_insignia#cite_note-14cfr1221-9> These
NASA emblems should be reproduced only from original reproduction proofs,
transparencies, or computer files available from NASA Headquarters."

So I think a SNIS version of the NASA "worm" logo might be in the clear.

**Comment by ProfessorKaos64** [comment]
I used images that were labelled for reuse, or with modification, per google image. Here's what I came up with in 15 minutes in GIMP.

https://github.com/ProfessorKaos64/SteamOS-Tools/blob/brewmaster/artwork/games/snis.png

**Comment by ProfessorKaos64** [comment]
I have to fix it up just a bit.

**Comment by smcameron** [comment]
What is the desired image size(s) for icons?  That seems big for an icon.

**Comment by ProfessorKaos64** [comment]
Steam Banners are 460x215. Sorry I did not clarify this was for Big Picture Mode on Steam. I have to head to bed, but I could come up with something as well with square dimensions.

**Comment by smcameron** [comment]
Maybe incorporate something like... http://i.imgur.com/YjzQRpo.png ?

**Comment by ProfessorKaos64** [comment]
Ok, now I really have to go to bed. Maybe a rough draft on the icon. Maybe something like this?

![snis_96x96](https://cloud.githubusercontent.com/assets/3931917/11330538/dcefccc8-917a-11e5-8119-22622f90178c.png)

https://github.com/ProfessorKaos64/SteamOS-Tools/blob/brewmaster/artwork/icons/snis_96x96.png
