### ISSUE TITLE
Error  building on Debian 8 / SteamOS

### ISSUE THREAD

**Issue by ProfessorKaos64** [smcameron/space-nerds-in-space#77]
```
  LINK snis_limited_client
  COMPILE mesh_viewer.c
  LINK mesh_viewer
make[2]: *** No rule to make target 'share/snis/planet_materials.txt', needed by 'install'.  Stop.
make[2]: Leaving directory '/home/desktop/build-snis-temp/snis'
debian/rules:36: recipe for target 'override_dh_auto_install' failed
make[1]: *** [override_dh_auto_install] Error 2
make[1]: Leaving directory '/home/desktop/build-snis-temp/snis'
debian/rules:22: recipe for target 'binary' failed
make: *** [binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2

Time started: 07:07:44
Time started: 07:21:50
Total Runtime (minutes): 14.10
```

* [Build script](https://github.com/ProfessorKaos64/SteamOS-Tools-Packaging/blob/brewmaster/build-snis.sh)

**Comment by smcameron** [comment]
Thank you for reporting this.  I think I know what the cause of this is but
it will be later on tonight before I can do anything about it.

-- steve

**Comment by ProfessorKaos64** [comment]
Thank you @smcameron , I'm just happy to be able to offer this to people on SteamOS / Debian 8. I even made an icon and Steam artbox :) . If you want the entire build log, let me know and I will upload it later this evening.

**Comment by kayila** [comment]
You know... it would be pretty cool if this was put up on Steam... just a
thought. :)

**Comment by ProfessorKaos64** [comment]
Ha I have no idea about that process. I host the deb for SteamOS-Tools. 

On December 10, 2015 12:55:46 PM EST, kayila <notifications@github.com> wrote:
>You know... it would be pretty cool if this was put up on Steam... just
>a
>thought. :)
>On Dec 10, 2015 10:47 AM, "mikeyd" <notifications@github.com> wrote:
>
>> Thank you @smcameron <https://github.com/smcameron> , I'm just happy
>to
>> be able to offer this to people on SteamOS / Debian 8. I even made an
>icon
>> and Steam artbox :) . If you want the entire build log, let me know
>and I
>> will upload it later this evening.
>>
>> —
>> Reply to this email directly or view it on GitHub
>>
><https://github.com/smcameron/space-nerds-in-space/issues/77#issuecomment-163665074>
>> .
>>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/smcameron/space-nerds-in-space/issues/77#issuecomment-163702363

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by smcameron** [comment]
Try top of tree now.  I think commit 8f0bc13d6b27eb4381e79c9710b365bdd817e43d should fix this.

**Comment by ProfessorKaos64** [comment]
Will do when I get home this evening, thank you for checking into this @smcameron .

**Comment by ProfessorKaos64** [comment]
worked great, thank you :)
