### ISSUE TITLE
Missing crater.h

### ISSUE THREAD

**Issue by DusteDdk** [smcameron/space-nerds-in-space#78]
Buildlog here http://contigrator.wizznic.org/jobs/space-nerds-in-space/builds/0637/BuildLog.txt

**Comment by smcameron** [comment]
Oops.  996a037700c7a71e48668ad3bb8844e13aadc792 should fix that.

**Comment by smcameron** [comment]
I noticed here: http://contigrator.wizznic.org/jobs/space-nerds-in-space/builds/0638/BuildLog.txt

/usr/bin/ld: i386:x86-64 architecture of input file `util/mask_clouds.o' is incompatible with i386 output
/usr/bin/ld: util/mask_clouds.o: file class ELFCLASS64 incompatible with ELFCLASS32
/usr/bin/ld: final link failed: File in wrong format
collect2: error: ld returned 1 exit status
Makefile:652: recipe for target 'util/mask_c

However, I am not seeing this on my systems (all 64 bit at this point though.)

**Comment by smcameron** [comment]
The crater.h issue is fixed... the other issue noted above is separate, can create another issue if need be.

**Comment by smcameron** [comment]
Hi...

Noticed that lately the builds are failing here:
http://contigrator.wizznic.org/jobs/space-nerds-in-space/builds/lastFailure/BuildLog.txt

Looks like some dependency creep...

snis_hash.c:23:25: fatal error: openssl/md5.h: No such file or directory
#include <openssl/md5.h> ^ compilation terminated.

... just in case you're interested in looking into it.

-- steve

**Comment by DusteDdk** [comment]
Hey! Sorry for the loong wait! Just saw this, I'll try and fix it :)
