### ISSUE TITLE
Space stations should always be identified on Science, Helm & Weapons

### ISSUE THREAD

**Issue by kwadroke** [smcameron/space-nerds-in-space#8]
Since Space Stations should be in known places on the map in the universe for friendlies, they should always be marked on each of the stations (Sci, Weapons, Helm). 

Another way to possibly handle this, is to have Comms send out a broadcast to all stations and have the stations give their positions upon this request. The screens could then update with the information.
Range could be reduced for this to not identify farther out stations.

**Comment by smcameron** [comment]
I'm going to go ahead and close this as I think the abovementioned changes address the main complaint.  Feel free to re-open and clarify if you don't agree.
