### ISSUE TITLE
Artifacts between near and far rendering passes

### ISSUE THREAD

**Issue by smcameron** [smcameron/space-nerds-in-space#80]
Rendering is done in two passes due to limited z buffer precision.  This can sometimes cause artifacts.

Example:
![Imgur](http://i.imgur.com/wPSEdxn.jpg)

And a closeup:
![Imgur](http://i.imgur.com/FRV54zY.jpg)
In still shots, it doesn't look too bad, but when the scene is moving these artifacts unfortunately jump around a bit and draw attention to themselves.  It seems to be most problematic with alpha-blended textures.

One idea:  dynamically choose the distance between passes on each frame such that it does not intersect any planets.   Nebula may be problematic though.

Another idea: logarthmic depth buffer (though this may have its own issues).
- http://www.gamasutra.com/blogs/BranoKemen/20090812/85207/Logarithmic_Depth_Buffer.php
- A demo: http://threejs.org/examples/webgl_camera_logarithmicdepthbuffer.html

**Comment by smcameron** [comment]
I think I have fixed this, or drastically improved it with the following to commits:

* 59026563ade8d14e653f9c45aa11bf5843afcad3  Dynamically calculate the boundary distance between rendering passes. 
* 1358f48c23fae6884908b04de5d977e463bf7ee8 Change main camera near plane from 1.0 to 5.0. 

Changing the near plane from 1.0 to 5.0 moves the boundary between the rendering passes from 10000 units to 50000 units for the main screen and weapons.  10000 was a particularly bad distance, as whenever you got near a planet, it was pretty much guaranteed to intersect this distance, and the artifacts seemed particularly bad on the planets as they kind of doubled up on the atmosphere and planet surface.  Putting it at 50000 makes it so the planets generally don't intersect the rendering boundary when you're near them.  So far, my attempts to reproduce the artifacts on planets at a distance of 50000 where they should be intersecting the new boundary and should potentially produce the artifacts have not been successful.  Or I should say, they have been successful in *not* producing the artifacts.  So, surprisingly these changes appear to *totally* fix the problem!

The following image shows two instances of the client running, the one in the upper left does not have this fix, the one in the lower right does have the fix.  Note the blue arc crossing the planet's surface indicated by the red arrow in the client in the upper left.
![rendering-artifact](https://user-images.githubusercontent.com/23912/56085597-13706280-5e14-11e9-858f-56d259ba2d46.jpg)

**Comment by MCMic** [comment]
Great news, this one was annoying me.

**Comment by smcameron** [comment]
Well, all is not fixed... after a bit more experimenting, I came across some z-fighting with distant objects and some new problem with the central star billboard. Although the experience of driving through nebula is *vastly* improved.

Here are some problems which are now present that weren't previously:

![sun-artifact](https://user-images.githubusercontent.com/23912/56092465-756baf00-5e8a-11e9-9d1c-f21805722aca.jpg)

This was while the ship was at (49973, -250027, 268880) as reported on the Nav screen. (the central star is always at (300000, 0, 300000)).

![z-fighting](https://user-images.githubusercontent.com/23912/56092485-b9f74a80-5e8a-11e9-9724-d5f8df44129b.jpg)

Above, we see the atmosphere z-fighting with the planet surface. In game, it's worse than this, as it's shimmering and moving, and so draws attention to itself more than this static image.  On the bright side, this image is with high-zoom level on the main screen.  With zoom at normal, it looks like this:

![z-fighting2](https://user-images.githubusercontent.com/23912/56092499-e743f880-5e8a-11e9-8f04-4e8c8764b3c5.jpg)

And here's another artifact.  This isn't z-fighting as rocky planet's do not have any atmosphere, rather I think it's the boundary between rendering passes.

![z-fighting3](https://user-images.githubusercontent.com/23912/56092516-10fd1f80-5e8b-11e9-97b7-8cef042f1569.jpg)

**Comment by smcameron** [comment]
Ha, another problem, the guns on weapons disappeared due to getting clipped by the near plane:

![guns-disappeared](https://user-images.githubusercontent.com/23912/56093077-380b1f80-5e92-11e9-8fab-4b081512f288.jpg)

**Comment by smcameron** [comment]
e271a8b67390386264a4789bab811e732a2c27b9 should fix the guns clipping issue by moving the near clipping plane close enough.  The weapons screen will then have the visible seam between rendering passes on nearby planets and nebula, and the perspective transform for weapons and main screen is now slightly different, so switching rapidly between them, you can notice nearby objects are slightly different sizes. Not a big deal, really.

It also tweaks the rendering pass boundary.

There are still some artifacts of course.  Below we see two things, first there is a seam visible between the rendering passes, and secondly, we see that there is no z-fighting in the far pass (because we are at the near end of the far pass where z-buffer depth precision is highest) and there is loads of z-fighting in the near pass (as we are at the far end of the near pass where z-buffer depth precision is lowest). It doesn't help that the atmosphere is only slightly larger than the planet, so all the triangles are necessarily close in z-values.  At least this is at a very high zoom level, so at normal zoom levels all this nonsense only occupies a small fraction of the field of view.

![render-pass-boundary](https://user-images.githubusercontent.com/23912/56094183-414eb900-5e9f-11e9-9ace-d7e94ff2a208.jpg)

**Comment by smcameron** [comment]
Fixed a stupid mistake: 69d00ee434279c51a45e5f7cd3e0896a11d73a3e

I was multiplying by the camera->near plane distance twice.  Which explains why the render pass boundary artifacts were appearing much further away than I thought they should.

With this change z-fighting is greatly reduced, but the original artifact is back, although at a different (slightly farther) distance.  This could use some more tweaking, and again, it might be interesting to try to choose the rendering pass boundary to avoid objects, however, this might mean another loop through all the objects.  Not sure.  The camera transform is computed using the render pass boundary though, and the camera transform is used in the first loop through the objects.  But it might be only using the angle of view, which should be the same regardless of render pass boundary, so it might be possible to change the render pass boundary after that first loop.  If so, then choosing a render pass boundary to avoid objects might be not too hard.

**Comment by smcameron** [comment]
With 2e0fcaa9879805903ebc9575def179da2e827999 it should now avoid visible seams, and have good zbuffer depth precision in most cases. This is done by having 3 candidate distances between the two rendering passes and for each frame choosing the candidate which intersects the fewest large objects.  In the vast majority of cases we will be able to choose a boundary distance between passes which intersects zero large objects, which will completely avoid visible seams.
