### ISSUE TITLE
libssl-dev is a dependency but isn't mentioned

### ISSUE THREAD

**Issue by daviddwk** [smcameron/space-nerds-in-space#84]
I sorry if I am mistaken, or maybe this package is supposed to be included in another mentioned dependency. Still, following the instructions to make a .deb and to compile normally gave me the error "snis_hash.c:23:25: fatal error: openssl/md5.h: No such file or directory compilation terminated." on both Debian testing and Ubuntu 16. Installing libssl-dev fixed the issue.

**Comment by smcameron** [comment]
You're not mistaken.  Added libssl-dev to the list of dependencies in the README with commit 8fc10ab777b3bab3f926f2f24387f62df0997443 

I didn't update the debian/control file though because I wasn't sure how to test it.
