### ISSUE TITLE
Build issue on SteamOS/Debian 8 - cannot find snis_multiverse

### ISSUE THREAD

**Issue by ProfessorKaos64** [smcameron/space-nerds-in-space#86]
I am having trouble building SNIS. It gets to the install phase, but cannot find snis_multiverse. The full build log is here: http://sprunge.us/eGhc. `snis_multiverse` is not being dumped into bin, but instead the source directory root.

Are you missing the entry [roughly here](https://github.com/smcameron/space-nerds-in-space/blob/master/Makefile#L651)? It is not being copied into bin/. I was going to submit a PR for this, but I wanted to be sure that was the intention, as I am not a developer in a traditional sense.

The problem to me, is the Makefile is trying to source snis_multiverse from bin/ and it's not there because it wasn't copied into bin/, like the otherse in the prior line link.

```
for x in ${PROGS} ; do \
		${INSTALL} -m 755 bin/$$x \
				${DESTDIR}/${PREFIX}/bin; \
	done
```

Errors:
```
make[1]: Entering directory '/build/snis-20160524+git+bsos'
/usr/bin/make DESTDIR=$(pwd)/debian/snis PREFIX=/usr install
make[2]: Entering directory '/build/snis-20160524+git+bsos'
./gather_build_info > build_info.h
  COMPILE snis_server.c
  LINK snis_server
  COMPILE snis_client.c
  LINK snis_client
cp snis_client.c snis_limited_client.c
  COMPILE snis_limited_client.c
  LINK snis_limited_client
  COMPILE mesh_viewer.c
  LINK mesh_viewer
  COMPILE snis_multiverse.c
  LINK snis_multiverse
gzip -9 - < snis_client.6 > snis_client.6.gz
gzip -9 - < snis_server.6 > snis_server.6.gz
gzip -9 - < earthlike.1 > earthlike.1.gz
mkdir -p /build/snis-20160524+git+bsos/debian/snis//usr/bin
install -m 755 ssgl/ssgl_server /build/snis-20160524+git+bsos/debian/snis//usr/bin
for x in snis_server snis_client snis_limited_client mesh_viewer snis_multiverse ; do \
	install -m 755 bin/$x \
			/build/snis-20160524+git+bsos/debian/snis//usr/bin; \
done
install: cannot stat 'bin/snis_multiverse': No such file or directory
```

**Comment by smcameron** [comment]
Hi, please see the email I sent to your personal account.  I modified your patches slightly, and I think the problem with the change you made to the BINPROGS line is that it needs to have "bin/snis_multiverse" added, not just "snis_multiverse".   Other than that, squashing the last 2 patches together is probably a good idea, and also I need your Signed-off-by: line on the patches (see item 12 at the bottom of this page: https://github.com/smcameron/space-nerds-in-space/blob/master/CONTRIBUTING.md    I have sent you modified patches.  Let me know if you are ok with my changes, and I can commit them.

**Comment by ProfessorKaos64** [comment]
Replied to your email with the attached patches. Thank you Steve, sorry for the sloppy PR. I'll try to be more careful.

**Comment by smcameron** [comment]
Not a problem at all.  Thanks.

-- steve

**Comment by smcameron** [comment]
I think this is fixed now.  Feel free to re-open this if it turns out not to be.
