### ISSUE TITLE
SDL 1.2 still required

### ISSUE THREAD

**Issue by kwadroke** [smcameron/space-nerds-in-space#88]
Not really a bug per-say as its a documentation issue. 
When compiling from instructions on the README.md file on a fresh install of Debian, a SDL dependency library is missing. Not sure if the .h file in mesh_viewer.c was missed with the conversion to SDL2 or if it still needs SDL1.

```
mesh_viewer.c:5:21: fatal error: SDL/SDL.h: No such file or directory
 #include <SDL/SDL.h>
                     ^
compilation terminated.
Makefile:595: recipe for target 'mesh_viewer.o' failed
```

To fix this issue run the following command from Debian/Ubuntu
`apt-get install libsdl-dev`

**Comment by OldDragon2A** [comment]
It was missed.  The code is making references to functions that are not in SDL2.

**Comment by smcameron** [comment]
Can one of you send me a patch?  Since I can't reproduce the problem on my system, it's pretty hard to know if any fix I come up with actually fixes the problem.

$ make mesh_viewer
  COMPILE snis_faction.c
  COMPILE mesh.c
  COMPILE material.c
  COMPILE stl_parser.c
  COMPILE entity.c
  COMPILE matrix.c
  COMPILE quat.c
  COMPILE vec4.c
  COMPILE thrust_attachment.c
  COMPILE snis_keyboard.c
  COMPILE graph_dev_opengl.c
./gather_build_info > build_info.h
  COMPILE mesh_viewer.c
  LINK mesh_viewer
$

**Comment by smcameron** [comment]
Or at least send output from the compiler showing what it is that you're bumping into.

**Comment by smcameron** [comment]
Commit b1f13b646b2dc4fe702030f599ab3722c9caa8f2 may help avoid the problem.  mesh_viewer, which is the only thing that uses SDL, is now not built by default.  It is a utility program for viewing 3d models, and is not required to run the game.

**Comment by OldDragon2A** [comment]
Here is what you get if you try to build the utils without SDL 1.2.
```
Package sdl was not found in the pkg-config search path.
Perhaps you should add the directory containing 'sdl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'sdl' found
Package sdl was not found in the pkg-config search path.
Perhaps you should add the directory containing 'sdl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'sdl' found
  COMPILE mtwist.c
  COMPILE mathutils.c
  COMPILE quat.c
./gather_build_info > build_info.h
  COMPILE open-simplex-noise.c
  COMPILE png_utils.c
  LINK util/mask_clouds
  LINK util/cloud-mask-normalmap
  COMPILE snis_alloc.c
  COMPILE snis_socket_io.c
  COMPILE snis_marshal.c
  COMPILE bline.c
  COMPILE shield_strength.c
  COMPILE stacktrace.c
  COMPILE snis_ship_type.c
  COMPILE snis_faction.c
  COMPILE names.c
  COMPILE infinite-taunt.c
  COMPILE snis_damcon_systems.c
  COMPILE string-utils.c
  COMPILE c-is-the-locale.c
  COMPILE starbase_metadata.c
  COMPILE arbitrary_spin.c
  COMPILE snis_hash.c
  COMPILE ogg_to_pcm.c
  COMPILE wwviaudio.c
  COMPILE snis_ui_element.c
  COMPILE snis_font.c
  COMPILE snis_text_input.c
  COMPILE snis_typeface.c
  COMPILE snis_gauge.c
  COMPILE snis_button.c
  COMPILE snis_label.c
  COMPILE snis_sliders.c
  COMPILE snis_text_window.c
  COMPILE snis_strip_chart.c
  COMPILE mesh.c
  COMPILE material.c
  COMPILE stl_parser.c
  COMPILE entity.c
  COMPILE matrix.c
  COMPILE my_point.c
  COMPILE liang-barsky.c
  COMPILE joystick.c
  COMPILE vec4.c
  COMPILE thrust_attachment.c
  COMPILE docking_port.c
  COMPILE ui_colors.c
  COMPILE snis_keyboard.c
  COMPILE solarsystem_config.c
  COMPILE shader.c
  COMPILE graph_dev_opengl.c
  COMPILE opengl_cap.c
  COMPILE snis_graph.c
mesh_viewer.c:5:21: fatal error: SDL/SDL.h: No such file or directory
 #include <SDL/SDL.h>
                     ^
compilation terminated.
Makefile:612: recipe for target 'mesh_viewer.o' failed
make: *** [mesh_viewer.o] Error 1
```

The warnings at the beginning are because SDL 2 doesn't provide a pkg-config setup.  The header referenced is for SDL 1.2 and updating it to SDL2/SDL.h will just yield some undefined function errors.

Removing libsdl1.2-dev was all I needed to reproduce these.

**Comment by smcameron** [comment]
Thanks, that helps.

**Comment by smcameron** [comment]
> ... not sure if the .h file in mesh_viewer.c was missed with the conversiion to SDL2 ...

Turns out there was no such conversion (which explains why I didn't remember any such conversion.)

And it turns out doing such a conversion is not a 30 minute job.
https://wiki.libsdl.org/MigrationGuide

**Comment by OldDragon2A** [comment]
I had just assumed the whole project was once SDL1.x and then moved to SDL2.

Just reading through that guide could take 30 minutes.

**Comment by smcameron** [comment]
SDL is only required by mesh_viewer, which is not required to run the game, and which is no longer built by default (since b1f13b646b2dc4fe702030f599ab3722c9caa8f2).
