### ISSUE TITLE
text_to_speech not being copied into /usr/bin with the debian package

### ISSUE THREAD

**Issue by HUg0005** [smcameron/space-nerds-in-space#95]
I was trying out space nerds in space, been loving it so far, but when ever I install the debian binary (whether I build it or download the pre built package) it doesn't put `text_to_speech.sh` into the `/usr/bin` folder which breaks the text to speech function.
It is easy to patch this for anyone having the same problem by moving `text_to_speech.sh` to `/usr/bin` and making it executable. 

For the less acquaint in linux this can be done by downloading `text_to_speech.sh` from the [git repo](https://github.com/smcameron/space-nerds-in-space/blob/master/text_to_speech.sh) then running:
`sudo cp /path/to/text_to_speech.sh /usr/bin`
`sudo chmod +x /usr/bin/text_to_speech.sh`

If this problem can be fixed than that would be greatly appreciated.

**Comment by smcameron** [comment]
Thanks for reporting this.  I haven't done a very good job of packaging this up, I generally just run it in place after having built it from source.  I made two commits which may help:

da76d0ad1a6505dfef378cdba7b5e8585d7ee369
7f73c2b99c594b2708d255b4830a69378ea6f23f

Since it seems to want to install in /usr/bin, I figured best to rename the script to snis_text_to_speech.sh

**Comment by smcameron** [comment]
I also added a man page for snis_text_to_speech.sh since it apparently will wind up in /usr/bin and dropping things in /usr/bin without a man page is unforgivable.
e3412145e4fac0ea918f0df91d071f6d3227060e

Let me know if these changes fix (or don't fix) the problem.

**Comment by HUg0005** [comment]
I'm very busy atm so I probably won't be able to test it for a couple of days. So if anyone else wants to test and post the results that would be great.

**Comment by HUg0005** [comment]
I built the `.deb` file from source and installed it without any problems. `snis_client` ran fine but when I went to Coms and ran `/computer help`, nothing. The terminal didn't show anything unusual so I tried to run `snis_text_to_speech.sh 'hello'` but nothing happened. Is `snis_text_to_speech.sh` broken?

**Comment by smcameron** [comment]
What are the permissions on snis_text_to_speech.sh?

You can run pico2wave?
You can run play?
You can run aplay?
You can run espeak?

(the first 2 should be sufficient.)

Does the directory /tmp/snisttslockdir exist? (it should not).

Try adding editing snis_text_to_speech.sh (it is just a script) and adding "set -x"  as the
first line after the comments (just before "export SNISTTSLOCKDIR=/tmp/snisttslockdir").

Then try running it:

snis_text_to_speech.sh hello

It should print out something like this:

+ export SNISTTSLOCKDIR=/tmp/snisttslockdir
+ do_text_to_speech hello
+ get_lock
+ count=0
+ worked=0
+ [ 0 -lt 20 ]
+ mkdir /tmp/snisttslockdir
+ [ 0 = 0 ]
+ trap release_lock INT EXIT
+ worked=1
+ break
+ [ 1 != 1 ]
+ tmpfile=/tmp/tts-17673.wav
+ pico2wave -l=en-GB -w /tmp/tts-17673.wav hello
+ play -q --volume 0.33 /tmp/tts-17673.wav
+ /bin/rm -f /tmp/tts-17673.wav
+ release_lock
+ /bin/rmdir /tmp/snisttslockdir

**Comment by HUg0005** [comment]
Alright I tried running `sudo chmod +x /usr/bin/snis_text_to_speech.sh` but to no avail; I only have pico2wave installed; play, aplay and espeak just came back with an error saying they are not found; ` /tmp /snisttslockdir` doesn't exist and `snis_text_to_speech hello` (with the line edited) came back with:

````
 + do_text_to_speech export
 + get_lock 
 + count=0
 + worked=0
 + [ 0 -lt 20 ]
 + mkdir 
 + [ 1 = 0 ]
 + expr 0 + 1
 + count=1
 + sleep 1
 + [ 1 -lt 20 ]+ do_text_to_speech export
 + get_lock 
 + count=0
 + worked=0
 + [ 0 -lt 20 ]
 + mkdir 
 + [ 1 = 0 ]
 + expr 0 + 1
 + count=1
 + sleep 1
 + [ 1 -lt 20 ]
 + mkdir 
 + [ 1 = 0 ]
 + expr 1 + 1
 + count=2
 + sleep 1
 + [ 2 -lt 20 ]
 + mkdir 
 + [ 1 = 0 ]
 + expr 2 + 1
 + count=3
 + sleep 1
 + [ 3 -lt 20 ]
 + mkdir 
 + [ 1 = 0 ]
 + expr 3 + 1
 + count=4
 + sleep 1
 + [ 4 -lt 20 ]
 + mkdir 
 + [ 1 = 0 ]
 + expr 4 + 1
+ count=5
 + sleep 1
 + [ 5 -lt 20 ]
 + mkdir 
 + [ 1 = 0 ]
 + expr 5 + 1
 + count=6
 + sleep 1
 + [ 6 -lt 20 ]
 + mkdir 
 + [ 1 = 0 ]
 + expr 6 + 1
 + count=7
 + sleep 1
 + [ 7 -lt 20 ]
 + mkdir 
 + [ 1 = 0 ]
 + expr 7 + 1
 + count=8
 + sleep 1
 + [ 8 -lt 20 ]
 + mkdir 
 + [ 1 = 0 ]
 + expr 8 + 1
 + count=9
 + sleep 1
 + [ 9 -lt 20 ]
 + mkdir 
 + [ 1 = 0 ]
 + expr 9 + 1
 + count=10
 + sleep 1
 + [ 10 -lt 20 ]
 + mkdir 
 + [ 1 = 0 ]
 + expr 10 + 1
 + count=11
 + sleep 1
 + [ 11 -lt 20 ]
 + mkdir 
 + [ 1 = 0 ]
 + expr 11 + 1
 + count=12
 + sleep 1
 + [ 12 -lt 20 ]
 + mkdir 
 + [ 1 = 0 ]
 + expr 12 + 1
 + count=13
 + sleep 1
 + [ 13 -lt 20 ]
 + mkdir 
 + [ 1 = 0 ]
 + expr 13 + 1
 + count=14
 + sleep 1
 + [ 14 -lt 20 ]
 + mkdir 
 + [ 1 = 0 ]
 + expr 14 + 1
 + count=15
 + sleep 1
 + [ 15 -lt 20 ]
 + mkdir 
 + [ 1 = 0 ]
 + expr 15 + 1
 + count=16
 + sleep 1
 + [ 16 -lt 20 ]
 + mkdir 
 + [ 1 = 0 ]
 + expr 16 + 1
 + count=17
 + sleep 1
 + [ 17 -lt 20 ]
 + mkdir 
 + [ 1 = 0 ]
 + expr 17 + 1
 + count=18
 + sleep 1
 + [ 18 -lt 20 ]
 + mkdir 
 + [ 1 = 0 ]
 + expr 18 + 1
 + count=19
 + sleep 1
 + [ 19 -lt 20 ]
 + mkdir 
 + [ 1 = 0 ]
 + expr 19 + 1
 + count=20
 + sleep 1
 + [ 20 -lt 20 ]
 + [ 0 != 1 ]
 + exit 1
 + mkdir 
 + [ 1 = 0 ]
 + expr 1 + 1
 + count=2
 + sleep 1
 + [ 2 -lt 20 ]
 + mkdir 
 + [ 1 = 0 ]
 + expr 2 + 1
 + count=3
 + sleep 1
 + [ 3 -lt 20 ]
 + mkdir 
 + [ 1 = 0 ]
 + expr 3 + 1
 + count=4
 + sleep 1
 + [ 4 -lt 20 ]
 + mkdir 
 + [ 1 = 0 ]
 + expr 4 + 1
+ count=5
 + sleep 1
 + [ 5 -lt 20 ]
 + mkdir 
 + [ 1 = 0 ]
 + expr 5 + 1
 + count=6
 + sleep 1
 + [ 6 -lt 20 ]
 + mkdir 
 + [ 1 = 0 ]
 + expr 6 + 1
 + count=7
 + sleep 1
 + [ 7 -lt 20 ]
 + mkdir 
 + [ 1 = 0 ]
 + expr 7 + 1
 + count=8
 + sleep 1
 + [ 8 -lt 20 ]
 + mkdir 
 + [ 1 = 0 ]
 + expr 8 + 1
 + count=9
 + sleep 1
 + [ 9 -lt 20 ]
 + mkdir 
 + [ 1 = 0 ]
 + expr 9 + 1
 + count=10
 + sleep 1
 + [ 10 -lt 20 ]
 + mkdir 
 + [ 1 = 0 ]
 + expr 10 + 1
 + count=11
 + sleep 1
 + [ 11 -lt 20 ]
 + mkdir 
 + [ 1 = 0 ]
 + expr 11 + 1
 + count=12
 + sleep 1
 + [ 12 -lt 20 ]
 + mkdir 
 + [ 1 = 0 ]
 + expr 12 + 1
 + count=13
 + sleep 1
 + [ 13 -lt 20 ]
 + mkdir 
 + [ 1 = 0 ]
 + expr 13 + 1
 + count=14
 + sleep 1
 + [ 14 -lt 20 ]
 + mkdir 
 + [ 1 = 0 ]
 + expr 14 + 1
 + count=15
 + sleep 1
 + [ 15 -lt 20 ]
 + mkdir 
 + [ 1 = 0 ]
 + expr 15 + 1
 + count=16
 + sleep 1
 + [ 16 -lt 20 ]
 + mkdir 
 + [ 1 = 0 ]
 + expr 16 + 1
 + count=17
 + sleep 1
 + [ 17 -lt 20 ]
 + mkdir 
 + [ 1 = 0 ]
 + expr 17 + 1
 + count=18
 + sleep 1
 + [ 18 -lt 20 ]
 + mkdir 
 + [ 1 = 0 ]
 + expr 18 + 1
 + count=19
 + sleep 1
 + [ 19 -lt 20 ]
 + mkdir 
 + [ 1 = 0 ]
 + expr 19 + 1
 + count=20
 + sleep 1
 + [ 20 -lt 20 ]
 + [ 0 != 1 ]
 + exit 1
```
before I Ctl-C to kill it as it would've run for ever.

**Comment by smcameron** [comment]
Actually, no it wouldn't run forever, in fact it exited ("exit 1") after attempting 20 times to create /tmp/snisttslockdir at 1 second intervals.

So, it's failing to create /tmp/snisttslockdir for some reason.

aplay is part of the alsa-utils package
play is part of sox package
espeak is part of espeak package
pico2wave is part of libttspico-utils package

So, "sudo apt-get install sox" to get play.  You already have pico2wave.  The others are optional fallbacks if those two aren't around, but wouldn't hurt to install the others too.

That leaves the question of why it can't mkdir /tmp/snisttslockdir

I am guessing it's probably related to permissions.

If you edit the snis_text_to_speech.sh script and change the line which says:

```
   mkdir "$SNISTTSLOCKDIR" > /dev/null 2>&1
```

so that it instead says
```
  mkdir "$SNISTTSLOCKDIR"
```

Then run the script again and we should see what mkdir is complaining about.

My guess is "Permission denied".

What is the output of `ls -ld /tmp` ?

**Comment by smcameron** [comment]
Made commit b0073e0ae35e7ffdc93277cacadf1104fb0937ed to include the missed dependencies in the README.

**Comment by smcameron** [comment]
Output of `ls -ld /tmp` should be similar to

```
 $ ls -ld /tmp
drwxrwxrwt 10 root root 4096 Jan 24 20:02 /tmp
```

and the output of `stat /tmp` should be something like:

```
$ stat /tmp
  File: ‘/tmp’
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 802h/2050d	Inode: 23199745    Links: 10
Access: (1777/drwxrwxrwt)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2017-01-24 17:51:59.815085773 -0800
Modify: 2017-01-24 20:02:19.845730435 -0800
Change: 2017-01-24 20:02:19.845730435 -0800
 Birth: -
```

(note the 1777).

especially the drwxrwxrwt part.

If not, then try this:

```
sudo chmod 1777 /tmp
```

**Comment by smcameron** [comment]
With commit 2e22cd1a65bcc713cf62a92b5e3def044f3e7ecc I added a "--debug" flag to snis_text_to_speech.sh, so that if you run `snis_text_to_speech.sh --debug` it will attempt to diagnose what's wrong.  Normally, the output should look like this:

```
$ ./snis_text_to_speech.sh --debug
snis_text_to_speech debugging mode enabled
Testing /tmp
  File: ‘/tmp’
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 802h/2050d	Inode: 23199745    Links: 11
Access: (1777/drwxrwxrwt)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2017-01-24 17:51:59.815085773 -0800
Modify: 2017-01-24 20:53:51.905642500 -0800
Change: 2017-01-24 20:53:51.905642500 -0800
 Birth: -
    OK - Checking permissions on /tmp
    OK - Permissions on /tmp seem to be ok (1777)
    OK - Checking if we can create a directory in /tmp
    OK - Created directory in /tmp OK
    Ok - Checking if we can remove the directory in /tmp
    OK - Removed directory in /tmp OK
    OK - play is present and executable
    OK - play seems OK
    OK - aplay is present and executable
    OK - aplay seems OK
    OK - pico2wave is present and executable
    OK - pico2wave seems OK
    OK - espeak is present and executable
    OK - espeak seems OK
```

**Comment by HUg0005** [comment]
OK; I have finally had the time to do some testing (sorry for the long wait); The problem was that for some reason `pico2wave` wasn't playing anything and as soon as I installed `sox`, `espeak` or `alsa-utils` it worked fine (BTW: the `aplay` voice has terrible quality compared to the `play` voice). You should add `sox` to the dependencies list. 
Thank you for all your help and fast responses.
