### ISSUE TITLE
Setting the main view from the comms screen is a bit weird

### ISSUE THREAD

**Issue by Baggypants** [smcameron/space-nerds-in-space#96]
There a bunch of buttons at the top of the comms screen that set the main screen, There is a button called "Main" which does nothing. The other buttons throw the requested display on the main screen. To return to the out-of-the-window view you have to press one of the other buttons again, like it's a toggle.

**Comment by smcameron** [comment]
You are right, it does seem to be broken.  Thanks for reporting this.

**Comment by smcameron** [comment]
Ok, I think this commit should fix it: cacf3d1d7721916029b483f10df5315300b23103

Feel free to re-open this if you don't agree.
